{{ config(tags=["talemia", "commercial-intelligence"]) }}

{% set raw = talemia_raw_relation('talemia_opportunities') %}

{% if raw %}
select
    nullif(opportunity_id, '')::text as opportunity_id,
    nullif(opportunity_name_en, '')::text as opportunity_name_en,
    nullif(opportunity_name_ar, '')::text as opportunity_name_ar,
    coalesce(nullif(client_name, ''), 'Unknown')::text as client_name,
    coalesce(nullif(client_department, ''), 'Unknown')::text as client_department,
    coalesce(nullif(account_manager_name, ''), 'Unknown')::text as account_manager_name,
    coalesce(nullif(business_line_name, ''), 'Unknown')::text as business_line_name,
    coalesce(nullif(moe_classification, ''), 'Unknown')::text as sector_type,
    coalesce(nullif(opportunity_stage, ''), 'Unknown')::text as opportunity_stage,
    coalesce(nullif(workflow_state, ''), 'Unknown')::text as workflow_state,
    coalesce(nullif(winning_likelihood, ''), 'Unknown')::text as winning_likelihood,
    nullif(deal_type, '')::text as deal_type,
    nullif(regexp_replace(coalesce(contract_value, ''), '[^0-9.-]', '', 'g'), '')::numeric(14, 2) as contract_value,
    nullif(regexp_replace(coalesce(qualified_sales, ''), '[^0-9.-]', '', 'g'), '')::numeric(14, 2) as qualified_sales,
    nullif(regexp_replace(coalesce(converted_value_2026, ''), '[^0-9.-]', '', 'g'), '')::numeric(14, 2) as converted_value_2026,
    nullif(regexp_replace(coalesce(awarded_value, ''), '[^0-9.-]', '', 'g'), '')::numeric(14, 2) as awarded_value,
    nullif(regexp_replace(coalesce(win_probability, ''), '[^0-9.-]', '', 'g'), '')::numeric(10, 4) as win_probability,
    case when nullif(submission_year, '') ~ '^[0-9]{4}' then left(submission_year, 4)::integer end as submission_year,
    nullif(expected_award_quarter, '')::text as expected_award_quarter,
    case when nullif(created_date, '') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' then left(created_date, 10)::date end as created_date,
    case when nullif(submission_date, '') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' then left(submission_date, 10)::date end as submission_date,
    case when nullif(expected_award_date, '') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' then left(expected_award_date, 10)::date end as expected_award_date,
    case when nullif(award_date, '') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' then left(award_date, 10)::date end as award_date,
    case when nullif(loss_date, '') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' then left(loss_date, 10)::date end as loss_date,
    case when nullif(close_date, '') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' then left(close_date, 10)::date end as close_date,
    nullif(loss_reason, '')::text as loss_reason,
    nullif(competitor, '')::text as competitor,
    nullif(notes, '')::text as notes,
    coalesce(nullif(parse_status, ''), 'unknown')::text as parse_status,
    nullif(regexp_replace(coalesce(match_confidence, ''), '[^0-9.-]', '', 'g'), '')::numeric(10, 4) as match_confidence,
    nullif(parser_warning, '')::text as parser_warning,
    nullif(source_sheet, '')::text as source_sheet,
    nullif(source_row_number, '')::text as source_row_number,
    current_timestamp::timestamp as as_of_timestamp
from {{ raw }}
{% else %}
select
    null::text as opportunity_id,
    null::text as opportunity_name_en,
    null::text as opportunity_name_ar,
    null::text as client_name,
    null::text as client_department,
    null::text as account_manager_name,
    null::text as business_line_name,
    null::text as sector_type,
    null::text as opportunity_stage,
    null::text as workflow_state,
    null::text as winning_likelihood,
    null::text as deal_type,
    null::numeric(14, 2) as contract_value,
    null::numeric(14, 2) as qualified_sales,
    null::numeric(14, 2) as converted_value_2026,
    null::numeric(14, 2) as awarded_value,
    null::numeric(10, 4) as win_probability,
    null::integer as submission_year,
    null::text as expected_award_quarter,
    null::date as created_date,
    null::date as submission_date,
    null::date as expected_award_date,
    null::date as award_date,
    null::date as loss_date,
    null::date as close_date,
    null::text as loss_reason,
    null::text as competitor,
    null::text as notes,
    null::text as parse_status,
    null::numeric(10, 4) as match_confidence,
    null::text as parser_warning,
    null::text as source_sheet,
    null::text as source_row_number,
    current_timestamp::timestamp as as_of_timestamp
where false
{% endif %}
