import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const out = resolve("output/module01-discovery-tests/editor"); mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ channel: "msedge", headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
  page.on("dialog", d => d.accept());
  await page.goto("http://127.0.0.1:3100/use-cases/data-ai-capability-diagnostic", { waitUntil: "networkidle" });
  await page.locator("#industry-profile").selectOption("manufacturing");
  await page.getByRole("button", { name: "Seed selected data", exact: true }).click();
  const capture = page.locator(".discovery-capture");
  await capture.getByText("Current and future use cases (2)", { exact: true }).click();
  await capture.getByRole("button", { name: "Remove use case", exact: true }).last().click();
  await capture.getByLabel("Future opportunities").selectOption("none");
  await capture.getByRole("button", { name: "Add use case", exact: true }).click();
  await capture.getByLabel("Name", { exact: true }).last().fill("Daily quality exceptions");
  await capture.getByLabel("Decision or problem addressed").last().fill("Assign owners to unresolved quality exceptions.");
  await capture.getByText("Current-state architecture", { exact: true }).click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("module01:industry-assessment:v1")));
  await page.route("**/api/reports/module01/architecture", route => route.fulfill({ json: { nodes: saved.discovery.architecture.nodes, edges: saved.discovery.architecture.edges, origin: "ai_draft", model: "mock-test", generatedAt: new Date().toISOString() } }));
  await capture.getByRole("button", { name: "Generate AI diagram draft", exact: true }).click();
  await capture.getByText("Draft generated; confirmation outstanding.", { exact: true }).waitFor();
  await capture.getByLabel("I confirm the depicted components and connections reflect the current state").check();
  await capture.getByLabel("Component 1", { exact: true }).fill("Manufacturing execution system - validated label");
  assert.equal(await capture.getByLabel("I confirm the depicted components and connections reflect the current state").isChecked(), false);
  await capture.getByRole("button", { name: "Remove component 3", exact: true }).click();
  let stored = await page.evaluate(() => JSON.parse(localStorage.getItem("module01:industry-assessment:v1")));
  assert.equal(stored.discovery.architecture.nodes.length, 2);
  assert.equal(stored.discovery.architecture.edges.length, 1);
  assert.equal(stored.discovery.useCases[1].name, "Daily quality exceptions");
  assert.equal(stored.discovery.futureUseCases, "none");
  await capture.locator(".discovery-diagram").screenshot({ path: resolve(out, "architecture-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await capture.locator(".discovery-diagram").screenshot({ path: resolve(out, "architecture-mobile.png") });
  assert.equal(await capture.evaluate(el => el.scrollWidth <= el.clientWidth + 2), true);
  await page.reload({ waitUntil: "networkidle" });
  stored = await page.evaluate(() => JSON.parse(localStorage.getItem("module01:industry-assessment:v1")));
  assert.equal(stored.discovery.architecture.nodes.length, 2);
  assert.equal(stored.discovery.useCases[1].name, "Daily quality exceptions");
  assert.equal(stored.discovery.futureUseCases, "none");
  writeFileSync(resolve(out, "results.json"), JSON.stringify({ status: "passed", gateway: "mocked explicitly", checks: ["use case CRUD", "no future use cases", "architecture edit and remove", "confirmation reset", "persistence", "mobile overflow"] }, null, 2));
  console.log("PASS discovery editor: use-case CRUD, optional future cases, architecture generation (mocked), edit/remove, confirmation reset, persistence and mobile.");
} finally { await browser.close(); }
