name: opencare
version: 0.1.0
config-version: 2

profile: opencare

model-paths:
  - models
macro-paths:
  - macros

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  opencare:
    +materialized: view
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics
    dictionary:
      +materialized: table
      +schema: dictionary
    revenue_cycle:
      staging:
        +materialized: view
        +schema: staging
      marts:
        +materialized: table
        +schema: analytics
    talemia:
      staging:
        +materialized: view
        +schema: staging
      marts:
        +materialized: table
        +schema: analytics
      dictionary:
        +materialized: table
        +schema: dictionary
