DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname = __SUPERSET_READONLY_USER_LITERAL__
  ) THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', __SUPERSET_READONLY_USER_LITERAL__, __SUPERSET_READONLY_PASSWORD_LITERAL__);
  ELSE
    EXECUTE format('ALTER ROLE %I WITH LOGIN PASSWORD %L', __SUPERSET_READONLY_USER_LITERAL__, __SUPERSET_READONLY_PASSWORD_LITERAL__);
  END IF;
END $$;

SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), __SUPERSET_READONLY_USER_LITERAL__) \gexec
GRANT USAGE ON SCHEMA analytics TO __SUPERSET_READONLY_USER_IDENTIFIER__;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO __SUPERSET_READONLY_USER_IDENTIFIER__;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO __SUPERSET_READONLY_USER_IDENTIFIER__;

REVOKE ALL ON SCHEMA raw FROM __SUPERSET_READONLY_USER_IDENTIFIER__;
REVOKE ALL ON SCHEMA output FROM __SUPERSET_READONLY_USER_IDENTIFIER__;
REVOKE ALL ON SCHEMA staging FROM __SUPERSET_READONLY_USER_IDENTIFIER__;
REVOKE ALL ON SCHEMA dictionary FROM __SUPERSET_READONLY_USER_IDENTIFIER__;
