DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname = :'SUPERSET_READONLY_USER'
  ) THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', :'SUPERSET_READONLY_USER', :'SUPERSET_READONLY_PASSWORD');
  ELSE
    EXECUTE format('ALTER ROLE %I WITH LOGIN PASSWORD %L', :'SUPERSET_READONLY_USER', :'SUPERSET_READONLY_PASSWORD');
  END IF;
END $$;

SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'SUPERSET_READONLY_USER') \gexec
GRANT USAGE ON SCHEMA analytics TO :"SUPERSET_READONLY_USER";
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO :"SUPERSET_READONLY_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO :"SUPERSET_READONLY_USER";

REVOKE ALL ON SCHEMA raw FROM :"SUPERSET_READONLY_USER";
REVOKE ALL ON SCHEMA output FROM :"SUPERSET_READONLY_USER";
REVOKE ALL ON SCHEMA staging FROM :"SUPERSET_READONLY_USER";
REVOKE ALL ON SCHEMA dictionary FROM :"SUPERSET_READONLY_USER";
