postgresql:
  enabled: false

minio:
  enabled: false

ingress:
  enabled: false

connectorBuilderServer:
  enabled: true

temporal:
  extraEnv:
    - name: SQL_TLS_ENABLED
      value: "false"
    - name: POSTGRES_TLS_ENABLED
      value: "false"

global:
  edition: community
  airbyteUrl: __AIRBYTE_WEBAPP_SERVICE_NAME__
  deploymentMode: oss
  auth:
    enabled: false
  database:
    type: external
    secretName: __AIRBYTE_SECRET_NAME__
    host: __POSTGRES_HOST__
    port: "__POSTGRES_PORT__"
    database: __AIRBYTE_DB_NAME__
    name: __AIRBYTE_DB_NAME__
    user: __AIRBYTE_DB_USER__
    userSecretKey: database-user
    passwordSecretKey: database-password
  storage:
    type: S3
    secretName: __AIRBYTE_SECRET_NAME__
    storageSecretName: __AIRBYTE_SECRET_NAME__
    bucket:
      log: __AIRBYTE_BUCKET_LOG__
      state: __AIRBYTE_BUCKET_STATE__
      workloadOutput: __AIRBYTE_BUCKET_WORKLOAD_OUTPUT__
      activityPayload: __AIRBYTE_BUCKET_ACTIVITY_PAYLOAD__
      auditLogging: __AIRBYTE_BUCKET_AUDIT_LOGGING__
      profilerOutput: __AIRBYTE_BUCKET_PROFILER_OUTPUT__
    s3:
      region: __MINIO_REGION__
      endpoint: __MINIO_ENDPOINT__
      authenticationType: credentials
      accessKeyIdSecretKey: aws-s3-access-key-id
      secretAccessKeySecretKey: aws-s3-secret-access-key
      pathStyleAccess: __AIRBYTE_S3_PATH_STYLE__
  env_vars:
    AIRBYTE_CONNECTOR_REGISTRY_ENTERPRISE_ENTERPRISE_SOURCE_STUBS_URL: __AIRBYTE_ENTERPRISE_SOURCE_STUBS_URL__
    AIRBYTE_CONNECTOR_REGISTRY_ENTERPRISE_ENTERPRISE_DESTINATION_STUBS_URL: __AIRBYTE_ENTERPRISE_DESTINATION_STUBS_URL__
    AIRBYTE_CONNECTOR_REGISTRY_ENTERPRISE_ENABLED: "__AIRBYTE_CONNECTOR_REGISTRY_ENTERPRISE_ENABLED__"
    RUN_DATABASE_MIGRATION_ON_STARTUP: "__RUN_DATABASE_MIGRATION_ON_STARTUP__"
    CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: __CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION__
    JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: __JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION__
    AIRBYTE_FLYWAY_CONFIGS_MINIMUM_MIGRATION_VERSION: __AIRBYTE_FLYWAY_CONFIGS_MINIMUM_MIGRATION_VERSION__
    AIRBYTE_FLYWAY_JOBS_MINIMUM_MIGRATION_VERSION: __AIRBYTE_FLYWAY_JOBS_MINIMUM_MIGRATION_VERSION__
    INTERNAL_API_TOKEN: __INTERNAL_API_TOKEN__
    AWS_REGION: __MINIO_REGION__
    AWS_DEFAULT_REGION: __MINIO_REGION__

server:
  service:
    type: ClusterIP

worker: {}
cron: {}

workloadLauncher:
  extraEnv:
    - name: SQL_TLS_ENABLED
      value: "false"
    - name: POSTGRES_TLS_ENABLED
      value: "false"
