export type DataAiDiagnosticQuestion = {
  id: string;
  number: number;
  domainId: number;
  domainEn: string;
  domainAr: string;
  questionAr: string;
  questionEn: string;
  evidenceRequired: string;
  evidenceAvailable: string;
  isoReference: string;
  score: number | null;
  target: number;
  gap: number | null;
  priority: string;
  notes: string;
  actionPlan: string;
};

export type DataAiDiagnosticDomain = {
  id: number;
  nameEn: string;
  nameAr: string;
};

export type DataAiReportPrompt = {
  title: string;
  prompt: string;
};

export const dataAiDiagnosticDomains = [
  {
    "id": 1,
    "nameEn": "Data Strategy & Business Value",
    "nameAr": "استراتيجية البيانات والقيمة المؤسسية"
  },
  {
    "id": 2,
    "nameEn": "Data Governance & Operating Model",
    "nameAr": "حوكمة البيانات ونموذج التشغيل"
  },
  {
    "id": 3,
    "nameEn": "Data Architecture & Infrastructure",
    "nameAr": "البنية التحتية ومعمارية البيانات"
  },
  {
    "id": 4,
    "nameEn": "Data Quality & Master Data",
    "nameAr": "جودة البيانات والبيانات المرجعية"
  },
  {
    "id": 5,
    "nameEn": "Metadata, Catalogue & Data Lineage",
    "nameAr": "الميتاداتا والكتالوج وسلاسل النسب"
  },
  {
    "id": 6,
    "nameEn": "Reporting, Dashboards & Analytics",
    "nameAr": "التقارير ولوحات المؤشرات والتحليلات"
  },
  {
    "id": 7,
    "nameEn": "Artificial Intelligence & Use Cases",
    "nameAr": "الذكاء الاصطناعي وحالات الاستخدام"
  },
  {
    "id": 8,
    "nameEn": "Tools & Platforms",
    "nameAr": "الأدوات والمنصات"
  },
  {
    "id": 9,
    "nameEn": "People, Capabilities & Operating Model",
    "nameAr": "الفرق والقدرات ونموذج العمل"
  },
  {
    "id": 10,
    "nameEn": "Compliance, Privacy & Data Security",
    "nameAr": "الامتثال والخصوصية وأمن البيانات"
  },
  {
    "id": 11,
    "nameEn": "Data Sources & Data Flows",
    "nameAr": "مصادر البيانات وتدفقاتها"
  },
  {
    "id": 12,
    "nameEn": "Training Data & Organisational Impact",
    "nameAr": "ربط بيانات التدريب بالأثر المؤسسي"
  },
  {
    "id": 13,
    "nameEn": "Execution, Roadmap & Value Measurement",
    "nameAr": "التنفيذ وخارطة الطريق وقياس الأثر"
  }
] satisfies DataAiDiagnosticDomain[];

export const dataAiDiagnosticQuestions = [
  {
    "id": "q001",
    "number": 1,
    "domainId": 1,
    "domainEn": "Data Strategy & Business Value",
    "domainAr": "استراتيجية البيانات والقيمة المؤسسية",
    "questionAr": "هل توجد استراتيجية بيانات موثقة ومعتمدة تربط البيانات بالأهداف الاستراتيجية ومؤشرات الأداء المؤسسي؟",
    "questionEn": "Is there an approved data strategy that links data to strategic objectives and KPIs?",
    "evidenceRequired": "Strategy document, roadmap, linkage to initiatives and KPIs",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 38505-1 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q002",
    "number": 2,
    "domainId": 1,
    "domainEn": "Data Strategy & Business Value",
    "domainAr": "استراتيجية البيانات والقيمة المؤسسية",
    "questionAr": "من هو المالك التنفيذي لاستراتيجية البيانات؟ وهل توجد لجنة أو مجلس بيانات بصلاحيات واضحة؟",
    "questionEn": "Who owns the data strategy? Is there a data council with clear authority?",
    "evidenceRequired": "Committee minutes, RACI, delegation frameworks",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 38505-1 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q003",
    "number": 3,
    "domainId": 1,
    "domainEn": "Data Strategy & Business Value",
    "domainAr": "استراتيجية البيانات والقيمة المؤسسية",
    "questionAr": "كيف يتم تحويل استراتيجية البيانات إلى محفظة مبادرات بأولويات وميزانيات ومسؤوليات؟",
    "questionEn": "How is the strategy translated into an initiative portfolio with priorities and budgets?",
    "evidenceRequired": "Roadmap, resource plan, initiative register",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q004",
    "number": 4,
    "domainId": 1,
    "domainEn": "Data Strategy & Business Value",
    "domainAr": "استراتيجية البيانات والقيمة المؤسسية",
    "questionAr": "ما المؤشرات التي تستخدمونها لإثبات أن مبادرات البيانات حسّنت القرار أو الأداء؟",
    "questionEn": "What metrics prove data initiatives improved decision-making or performance?",
    "evidenceRequired": "KPIs, benefits realisation, operational outcomes",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO/IEC 38505-1",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q005",
    "number": 5,
    "domainId": 1,
    "domainEn": "Data Strategy & Business Value",
    "domainAr": "استراتيجية البيانات والقيمة المؤسسية",
    "questionAr": "كيف يتم اختيار وترتيب أولويات حالات استخدام البيانات والتحليلات والذكاء الاصطناعي؟",
    "questionEn": "How are data, analytics and AI use cases selected and prioritised?",
    "evidenceRequired": "Value/complexity/risk matrix, use-case register",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | NIST AI RMF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q006",
    "number": 6,
    "domainId": 1,
    "domainEn": "Data Strategy & Business Value",
    "domainAr": "استراتيجية البيانات والقيمة المؤسسية",
    "questionAr": "إذا أردنا بناء منصة ذكاء مؤسسي موحدة، هل يمكن توحيد البيانات من جميع الأنظمة؟",
    "questionEn": "If building a unified intelligence platform, can all system data be consolidated?",
    "evidenceRequired": "Systems list, data flow maps, integration assessment",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q007",
    "number": 7,
    "domainId": 1,
    "domainEn": "Data Strategy & Business Value",
    "domainAr": "استراتيجية البيانات والقيمة المؤسسية",
    "questionAr": "ما أكبر عائق يمنع المؤسسة من التحول إلى مؤسسة قائمة على البيانات؟",
    "questionEn": "What is the biggest barrier to becoming a data-driven organisation?",
    "evidenceRequired": "Transformation readiness assessment, gap analysis",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q008",
    "number": 8,
    "domainId": 2,
    "domainEn": "Data Governance & Operating Model",
    "domainAr": "حوكمة البيانات ونموذج التشغيل",
    "questionAr": "كيف يتم تعريف وتصنيف البيانات المهمة؟ هل توجد رؤية واضحة للبيانات الحرجة؟",
    "questionEn": "How are critical data assets defined and classified?",
    "evidenceRequired": "Data dictionary, classification register",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO/IEC 11179",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q009",
    "number": 9,
    "domainId": 2,
    "domainEn": "Data Governance & Operating Model",
    "domainAr": "حوكمة البيانات ونموذج التشغيل",
    "questionAr": "هل توجد سياسة أو إطار حوكمة بيانات يغطي الملكية والجودة والوصول والخصوصية؟",
    "questionEn": "Is there a data governance policy covering ownership, quality, access and privacy?",
    "evidenceRequired": "Governance charter, approved policies",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 38505-1 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q010",
    "number": 10,
    "domainId": 2,
    "domainEn": "Data Governance & Operating Model",
    "domainAr": "حوكمة البيانات ونموذج التشغيل",
    "questionAr": "هل لكل نطاق بيانات مالك أعمال واضح مسؤول عن التعريف والجودة والاستخدام؟",
    "questionEn": "Does every data domain have a named business owner accountable for quality and usage?",
    "evidenceRequired": "Data ownership matrix, RACI",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO 8000-150",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q011",
    "number": 11,
    "domainId": 2,
    "domainEn": "Data Governance & Operating Model",
    "domainAr": "حوكمة البيانات ونموذج التشغيل",
    "questionAr": "هل توجد منظومة حوكمة تشمل مجلس بيانات وملاك وأمناء وآليات تصعيد؟",
    "questionEn": "Does a governance framework exist with a data council, owners, stewards and escalation paths?",
    "evidenceRequired": "Governance charter, defined roles, committees",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 38505-1 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q012",
    "number": 12,
    "domainId": 2,
    "domainEn": "Data Governance & Operating Model",
    "domainAr": "حوكمة البيانات ونموذج التشغيل",
    "questionAr": "هل توجد آلية موحدة لاعتماد تعريفات البيانات والمؤشرات؟",
    "questionEn": "Is there a unified mechanism for approving data definitions and KPI terminology?",
    "evidenceRequired": "Business glossary, definition approval register",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 11179 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q013",
    "number": 13,
    "domainId": 2,
    "domainEn": "Data Governance & Operating Model",
    "domainAr": "حوكمة البيانات ونموذج التشغيل",
    "questionAr": "عند وجود تعارض حول تعريف مؤشر أو جودة مصدر، كيف يتم اتخاذ القرار؟",
    "questionEn": "When conflicts arise over KPI definitions or source quality, how are they resolved?",
    "evidenceRequired": "Decision records, escalation path, issues register",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | ISO/IEC 38505-1",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q014",
    "number": 14,
    "domainId": 3,
    "domainEn": "Data Architecture & Infrastructure",
    "domainAr": "البنية التحتية ومعمارية البيانات",
    "questionAr": "ما الأنظمة الحالية المستخدمة لإدارة البرامج والتسجيل والحضور والاختبارات والشهادات؟",
    "questionEn": "What systems manage programmes, registration, attendance, assessments and certifications?",
    "evidenceRequired": "Systems list, architecture documents",
    "evidenceAvailable": "",
    "isoReference": "TOGAF | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q015",
    "number": 15,
    "domainId": 3,
    "domainEn": "Data Architecture & Infrastructure",
    "domainAr": "البنية التحتية ومعمارية البيانات",
    "questionAr": "هل الأنظمة متكاملة آلياً أم يتم تبادل البيانات عبر Excel أو إدخال يدوي؟",
    "questionEn": "Are systems integrated automatically, or does data exchange rely on Excel or manual entry?",
    "evidenceRequired": "Integration map, automated job logs",
    "evidenceAvailable": "",
    "isoReference": "TOGAF | ISO/IEC 19944",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q016",
    "number": 16,
    "domainId": 3,
    "domainEn": "Data Architecture & Infrastructure",
    "domainAr": "البنية التحتية ومعمارية البيانات",
    "questionAr": "هل توجد قاعدة بيانات موحدة أو مستودع بيانات يمثل مصدراً واحداً للحقيقة؟",
    "questionEn": "Is there a unified data store or warehouse representing a single source of truth?",
    "evidenceRequired": "Infrastructure docs, golden source policy",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q017",
    "number": 17,
    "domainId": 3,
    "domainEn": "Data Architecture & Infrastructure",
    "domainAr": "البنية التحتية ومعمارية البيانات",
    "questionAr": "هل توجد معمارية بيانات موثقة توضح المصادر والتكامل والتخزين والاستهلاك؟",
    "questionEn": "Is there a documented data architecture covering sources, integration, storage and consumption?",
    "evidenceRequired": "Architecture diagrams, data flow diagrams",
    "evidenceAvailable": "",
    "isoReference": "TOGAF | ISO/IEC 19944",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q018",
    "number": 18,
    "domainId": 3,
    "domainEn": "Data Architecture & Infrastructure",
    "domainAr": "البنية التحتية ومعمارية البيانات",
    "questionAr": "هل توجد بيئات منفصلة للتطوير والاختبار والإنتاج مع ضوابط وصول محكومة؟",
    "questionEn": "Are separate Dev, Test and Prod environments maintained with controlled access?",
    "evidenceRequired": "Environment docs, access controls, change management",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q019",
    "number": 19,
    "domainId": 3,
    "domainEn": "Data Architecture & Infrastructure",
    "domainAr": "البنية التحتية ومعمارية البيانات",
    "questionAr": "ما ضوابط التوافر والنسخ الاحتياطي والتعافي من الكوارث لمنصات البيانات؟",
    "questionEn": "What availability, backup and disaster recovery controls are in place for data platforms?",
    "evidenceRequired": "DR plans, RPO/RTO targets, backup reports",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q020",
    "number": 20,
    "domainId": 4,
    "domainEn": "Data Quality & Master Data",
    "domainAr": "جودة البيانات والبيانات المرجعية",
    "questionAr": "كيف يتم قياس جودة البيانات من حيث الاكتمال والدقة والاتساق والحداثة؟",
    "questionEn": "How is data quality measured — completeness, accuracy, consistency, timeliness?",
    "evidenceRequired": "Quality dimensions, validation rules, measurement results",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 25012 | ISO 8000-150",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q021",
    "number": 21,
    "domainId": 4,
    "domainEn": "Data Quality & Master Data",
    "domainAr": "جودة البيانات والبيانات المرجعية",
    "questionAr": "هل توجد حالات تكرار أو تضارب في البيانات بين الأنظمة المختلفة؟",
    "questionEn": "Are there duplication or conflict issues across different systems?",
    "evidenceRequired": "MDM reports, data quality analytics",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO/IEC 11179",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q022",
    "number": 22,
    "domainId": 4,
    "domainEn": "Data Quality & Master Data",
    "domainAr": "جودة البيانات والبيانات المرجعية",
    "questionAr": "هل توجد قواعد تحقق آلية على مصادر البيانات والمؤشرات؟",
    "questionEn": "Are automated validation rules applied to data sources and KPIs?",
    "evidenceRequired": "Data quality rules, validation logs, owner approvals",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 25012 | ISO 8000-150",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q023",
    "number": 23,
    "domainId": 4,
    "domainEn": "Data Quality & Master Data",
    "domainAr": "جودة البيانات والبيانات المرجعية",
    "questionAr": "عند اكتشاف مشكلة جودة بيانات، كيف يتم تسجيلها وعلاجها ومنع تكرارها؟",
    "questionEn": "When a data quality issue is found, how is it logged, remediated and prevented from recurring?",
    "evidenceRequired": "Issue register, root-cause analysis, SLA",
    "evidenceAvailable": "",
    "isoReference": "ISO 8000-150 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q024",
    "number": 24,
    "domainId": 4,
    "domainEn": "Data Quality & Master Data",
    "domainAr": "جودة البيانات والبيانات المرجعية",
    "questionAr": "هل توجد قوائم موحدة للمتدربين والمدربين والبرامج كبيانات مرجعية معتمدة؟",
    "questionEn": "Are unified reference lists maintained for trainees, trainers and programmes?",
    "evidenceRequired": "MDM rules, reference data tables, golden record logic",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO/IEC 11179",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q025",
    "number": 25,
    "domainId": 4,
    "domainEn": "Data Quality & Master Data",
    "domainAr": "جودة البيانات والبيانات المرجعية",
    "questionAr": "هل يوجد معرّف موحد لكل متدرب أو مدرب يمكن ربطه عبر جميع الأنظمة؟",
    "questionEn": "Is there a unified identifier for each trainee and trainer usable across all systems?",
    "evidenceRequired": "Identity management system, linking rules",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 11179 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q026",
    "number": 26,
    "domainId": 4,
    "domainEn": "Data Quality & Master Data",
    "domainAr": "جودة البيانات والبيانات المرجعية",
    "questionAr": "هل يتم قياس تكلفة ضعف جودة البيانات على الأخطاء والتأخير وإعادة العمل؟",
    "questionEn": "Is the cost of poor data quality measured — errors, rework, compliance failures?",
    "evidenceRequired": "Impact reports, rework costs, operational error cases",
    "evidenceAvailable": "",
    "isoReference": "ISO 8000-150 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q027",
    "number": 27,
    "domainId": 5,
    "domainEn": "Metadata, Catalogue & Data Lineage",
    "domainAr": "الميتاداتا والكتالوج وسلاسل النسب",
    "questionAr": "هل يوجد كتالوج بيانات يوضح المصادر والتعريفات والمالكين والتصنيف وسلاسل النسب؟",
    "questionEn": "Is there a data catalogue describing sources, definitions, owners, classification and lineage?",
    "evidenceRequired": "Data catalogue, metadata repository, lineage data",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 11179 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q028",
    "number": 28,
    "domainId": 5,
    "domainEn": "Metadata, Catalogue & Data Lineage",
    "domainAr": "الميتاداتا والكتالوج وسلاسل النسب",
    "questionAr": "هل تدار الميتاداتا التقنية والتجارية والتشغيلية ضمن سجل موحد؟",
    "questionEn": "Are technical, business and operational metadata managed in a unified registry?",
    "evidenceRequired": "Technical metadata, business glossary, operational metadata",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 11179 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q029",
    "number": 29,
    "domainId": 5,
    "domainEn": "Metadata, Catalogue & Data Lineage",
    "domainAr": "الميتاداتا والكتالوج وسلاسل النسب",
    "questionAr": "عندما يظهر رقم في تقرير تنفيذي، هل يمكن تتبعه إلى مصدره وقواعد التحويل؟",
    "questionEn": "When a number appears in an executive report, can it be traced to its source and transformation rules?",
    "evidenceRequired": "Lineage graph, transformation rules, audit trail",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q030",
    "number": 30,
    "domainId": 5,
    "domainEn": "Metadata, Catalogue & Data Lineage",
    "domainAr": "الميتاداتا والكتالوج وسلاسل النسب",
    "questionAr": "هل توجد خرائط تدفق بيانات موثقة تبيّن كيف تنتقل البيانات عبر الأنظمة؟",
    "questionEn": "Are documented data flow maps showing how data moves across systems?",
    "evidenceRequired": "Data flow and lineage maps, transformation docs",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO/IEC 19944",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q031",
    "number": 31,
    "domainId": 5,
    "domainEn": "Metadata, Catalogue & Data Lineage",
    "domainAr": "الميتاداتا والكتالوج وسلاسل النسب",
    "questionAr": "هل يوجد قاموس بيانات موحد وتعريفات معتمدة للمصطلحات والمؤشرات؟",
    "questionEn": "Is there a unified data dictionary with approved definitions for terms and KPIs?",
    "evidenceRequired": "Unified data dictionary, business glossary",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 11179 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q032",
    "number": 32,
    "domainId": 5,
    "domainEn": "Metadata, Catalogue & Data Lineage",
    "domainAr": "الميتاداتا والكتالوج وسلاسل النسب",
    "questionAr": "هل توجد اتفاقيات مستوى خدمة للبيانات تحدد حداثتها ودقتها وزمن تحديثها؟",
    "questionEn": "Are Data SLAs defined specifying freshness, accuracy, update frequency and source accountability?",
    "evidenceRequired": "Data contracts, SLA documents, freshness reports",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q033",
    "number": 33,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "هل توجد لوحة مؤشرات تنفيذية موحدة تعرض مؤشرات التدريب والجودة والأثر؟",
    "questionEn": "Is there a unified executive dashboard showing training, quality and impact indicators?",
    "evidenceRequired": "Unified dashboard, BI documentation",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q034",
    "number": 34,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "هل التقارير وصفية فقط أم تشمل تحليلاً تشخيصياً وتنبؤياً؟",
    "questionEn": "Are reports purely descriptive, or do they include diagnostic and predictive analysis?",
    "evidenceRequired": "Report samples, analysis examples, output descriptions",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK — Analytics Maturity",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q035",
    "number": 35,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "هل يمكن تحليل الفجوات التدريبية من البيانات لدعم قرارات التخطيط؟",
    "questionEn": "Can training gap analysis be derived from data to support planning decisions?",
    "evidenceRequired": "Learning analytics reports, competency matrices",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q036",
    "number": 36,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "هل توجد قائمة موحدة للتقارير؟ ومن يعتمد التقرير كمصدر رسمي؟",
    "questionEn": "Is there a unified report inventory? Who certifies a report as the official source of truth?",
    "evidenceRequired": "Report inventory, BI governance, certified datasets",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q037",
    "number": 37,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "عند اختلاف رقم بين تقريرين، كيف يتم تحديد الرقم الرسمي؟",
    "questionEn": "When two reports show different figures, how is the authoritative number determined?",
    "evidenceRequired": "KPI dictionary, certified metrics, reconciliation rules",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 11179 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q038",
    "number": 38,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "ما نسبة التقارير التي تعتمد على استخراج يدوي أو Excel؟",
    "questionEn": "What proportion of reports rely on manual extraction or Excel processing?",
    "evidenceRequired": "Process maps, manual steps documented, error logs",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | ISO/IEC 38505-1",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q039",
    "number": 39,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "ما التقارير التي تطلبها القيادة العليا بشكل متكرر وما مدة إعدادها؟",
    "questionEn": "What reports does senior leadership request regularly, and how long do they take to produce?",
    "evidenceRequired": "Executive report list, response times, automation level",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q040",
    "number": 40,
    "domainId": 6,
    "domainEn": "Reporting, Dashboards & Analytics",
    "domainAr": "التقارير ولوحات المؤشرات والتحليلات",
    "questionAr": "هل لكل مؤشر أداء تعريف وصيغة حساب ومصدر ومالك وحدود أداء معتمدة؟",
    "questionEn": "Does every KPI have a definition, formula, source, owner and approved performance thresholds?",
    "evidenceRequired": "KPI catalogue, calculation rules, data owner sign-off",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 11179 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q041",
    "number": 41,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "هل البيانات الحالية كافية من حيث الجودة والتغطية لبناء نماذج توصية أو تنبؤ؟",
    "questionEn": "Are current data assets sufficient in quality and coverage to build recommendation or prediction models?",
    "evidenceRequired": "Data readiness assessment, gap analysis",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 25012 | ISO/IEC 42001",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q042",
    "number": 42,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "ما مدى عمق البيانات التاريخية المتوفرة؟ وهل تكفي للتحليل التنبؤي؟",
    "questionEn": "How deep is the available historical data? Is it sufficient for predictive analysis?",
    "evidenceRequired": "Historical data availability reports, time span coverage",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 42001 | NIST AI RMF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q043",
    "number": 43,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "ما أبرز حالات استخدام الذكاء الاصطناعي ذات القيمة العالية في سياق عمل المؤسسة؟",
    "questionEn": "What are the highest-value AI use cases in the organisation's context?",
    "evidenceRequired": "Proposed use-case list, preliminary priorities",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 42001 | NIST AI RMF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q044",
    "number": 44,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "هل توجد خارطة طريق لحالات استخدام الذكاء الاصطناعي مرتبطة بجاهزية البيانات والمخاطر؟",
    "questionEn": "Is there an AI use-case roadmap linked to data readiness, value and risk classification?",
    "evidenceRequired": "AI use-case portfolio, risk classification, readiness score",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 42001 | ISO/IEC 23894",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q045",
    "number": 45,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "ما المعايير المستخدمة لاختيار حالات الاستخدام من حيث الأثر والجاهزية والمخاطر؟",
    "questionEn": "What criteria guide AI use-case selection — impact, readiness, risk, explainability?",
    "evidenceRequired": "Evaluation matrix, business case, risk assessment",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 42001 | ISO/IEC 23894",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q046",
    "number": 46,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "هل توجد ضوابط لاعتماد النماذج ومراقبة الانحياز والانجراف وإيقافها عند الحاجة؟",
    "questionEn": "Are there controls for model approval, bias monitoring, drift detection and decommissioning?",
    "evidenceRequired": "Model registry, monitoring dashboard, bias tests, approval workflow",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 42001 | NIST AI RMF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q047",
    "number": 47,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "هل توجد بيانات كافية لبناء نماذج تنبؤية للتدريب والاعتماد المهني؟",
    "questionEn": "Is sufficient data available to build predictive models for training and professional certification?",
    "evidenceRequired": "Predictive model readiness assessment, minimum data requirements",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 42001 | NIST AI RMF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q048",
    "number": 48,
    "domainId": 7,
    "domainEn": "Artificial Intelligence & Use Cases",
    "domainAr": "الذكاء الاصطناعي وحالات الاستخدام",
    "questionAr": "بعد تشغيل حالة استخدام للذكاء الاصطناعي، كيف يتم قياس أثرها على القرار والتكلفة؟",
    "questionEn": "After deploying an AI use case, how is its impact on decisions, time and cost measured?",
    "evidenceRequired": "Model KPIs, business impact report, monitoring dashboard",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 42001 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q049",
    "number": 49,
    "domainId": 8,
    "domainEn": "Tools & Platforms",
    "domainAr": "الأدوات والمنصات",
    "questionAr": "ما الأدوات المستخدمة حالياً: الاستخراج، التكامل، التخزين، التحويل، الكتالوج، التقارير، AI؟",
    "questionEn": "What tools are currently used across ingestion, integration, storage, transformation, BI and AI?",
    "evidenceRequired": "Tool inventory, licence list, architecture map",
    "evidenceAvailable": "",
    "isoReference": "TOGAF | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q050",
    "number": 50,
    "domainId": 8,
    "domainEn": "Tools & Platforms",
    "domainAr": "الأدوات والمنصات",
    "questionAr": "هل توجد تكاملات واضحة بين أدوات البيانات أم تعمل كل أداة بمعزل؟",
    "questionEn": "Are data tools integrated, or does each operate in isolation?",
    "evidenceRequired": "Integration map, APIs, workflow evidence",
    "evidenceAvailable": "",
    "isoReference": "TOGAF | ISO/IEC 38505-1",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q051",
    "number": 51,
    "domainId": 8,
    "domainEn": "Tools & Platforms",
    "domainAr": "الأدوات والمنصات",
    "questionAr": "هل يتم قياس استخدام الأدوات مقابل القيمة الفعلية؟ وهل توجد أدوات متكررة؟",
    "questionEn": "Is tool utilisation measured against actual value? Are there redundant tools performing the same function?",
    "evidenceRequired": "Licence utilisation reports, tool rationalisation plan",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q052",
    "number": 52,
    "domainId": 8,
    "domainEn": "Tools & Platforms",
    "domainAr": "الأدوات والمنصات",
    "questionAr": "هل تدعم الأدوات التحكم في الوصول والتصنيف والتدقيق وإدارة الموافقات؟",
    "questionEn": "Do tools support access control, classification, auditing and consent management?",
    "evidenceRequired": "Access logs, audit logs, RBAC, policy enforcement",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | ISO/IEC 27701",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q053",
    "number": 53,
    "domainId": 8,
    "domainEn": "Tools & Platforms",
    "domainAr": "الأدوات والمنصات",
    "questionAr": "عند اختيار أداة جديدة، هل تُقيَّم مقابل المعمارية والأمان والتكامل والتكلفة؟",
    "questionEn": "When selecting a new tool, is it evaluated against architecture, security, integration and cost criteria?",
    "evidenceRequired": "Selection criteria, architecture review, procurement governance",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q054",
    "number": 54,
    "domainId": 9,
    "domainEn": "People, Capabilities & Operating Model",
    "domainAr": "الفرق والقدرات ونموذج العمل",
    "questionAr": "ما الفرق والأدوار الحالية: هندسة بيانات، تقارير، حوكمة، جودة، أمن، ذكاء اصطناعي؟",
    "questionEn": "What data-related teams and roles currently exist — engineering, BI, governance, quality, security, AI?",
    "evidenceRequired": "Org chart, role descriptions, capability matrix",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO 8000-150",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q055",
    "number": 55,
    "domainId": 9,
    "domainEn": "People, Capabilities & Operating Model",
    "domainAr": "الفرق والقدرات ونموذج العمل",
    "questionAr": "هل توجد فجوة مهارية بين متطلبات الاستراتيجية والقدرات الحالية؟",
    "questionEn": "Is there a skills gap between data strategy requirements and current team capabilities?",
    "evidenceRequired": "Skills assessment, hiring plan, training plan",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q056",
    "number": 56,
    "domainId": 9,
    "domainEn": "People, Capabilities & Operating Model",
    "domainAr": "الفرق والقدرات ونموذج العمل",
    "questionAr": "كيف يتم توزيع المسؤولية بين إدارات الأعمال وتقنية المعلومات في مبادرات البيانات؟",
    "questionEn": "How is responsibility shared between business units and IT in data initiatives?",
    "evidenceRequired": "RACI, delivery model, product ownership",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 38505-1 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q057",
    "number": 57,
    "domainId": 9,
    "domainEn": "People, Capabilities & Operating Model",
    "domainAr": "الفرق والقدرات ونموذج العمل",
    "questionAr": "هل تدار البيانات كمنتجات مستدامة لها مالك ومستخدمون ومستويات خدمة؟",
    "questionEn": "Are data assets managed as sustainable products with owners, users, SLAs and lifecycle management?",
    "evidenceRequired": "Data product catalogue, owners, backlog, service metrics",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q058",
    "number": 58,
    "domainId": 9,
    "domainEn": "People, Capabilities & Operating Model",
    "domainAr": "الفرق والقدرات ونموذج العمل",
    "questionAr": "هل توجد مستندات تشغيلية ومعمارية وقواميس بيانات محدّثة؟",
    "questionEn": "Are operational and architecture documents and data dictionaries kept current?",
    "evidenceRequired": "Runbooks, data dictionary, architecture repository",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | ISO/IEC 11179",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q059",
    "number": 59,
    "domainId": 10,
    "domainEn": "Compliance, Privacy & Data Security",
    "domainAr": "الامتثال والخصوصية وأمن البيانات",
    "questionAr": "كيف يتم حماية بيانات المتدربين والمدربين؟ وهل توجد ضوابط وصول واضحة؟",
    "questionEn": "How are trainee and trainer data protected? Are clear access controls in place?",
    "evidenceRequired": "Security controls, access policies, protection records",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | PDPL",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q060",
    "number": 60,
    "domainId": 10,
    "domainEn": "Compliance, Privacy & Data Security",
    "domainAr": "الامتثال والخصوصية وأمن البيانات",
    "questionAr": "هل يتم تصنيف البيانات حسب حساسيتها؟ وهل يوجد نظام تصنيف رسمي؟",
    "questionEn": "Is data classified by sensitivity level using a formal, enforced classification scheme?",
    "evidenceRequired": "Classification policy, labels, handling rules",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | NDMO",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q061",
    "number": 61,
    "domainId": 10,
    "domainEn": "Compliance, Privacy & Data Security",
    "domainAr": "الامتثال والخصوصية وأمن البيانات",
    "questionAr": "هل توجد آلية لتتبع من يصل إلى البيانات أو يعدّلها؟",
    "questionEn": "Is there a mechanism to track who accesses or modifies data?",
    "evidenceRequired": "Access logs, audit logs, monitoring evidence",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | ISO/IEC 27002",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q062",
    "number": 62,
    "domainId": 10,
    "domainEn": "Compliance, Privacy & Data Security",
    "domainAr": "الامتثال والخصوصية وأمن البيانات",
    "questionAr": "ما المتطلبات التنظيمية التي تخضع لها البيانات؟ وكيف تم تحويلها إلى ضوابط؟",
    "questionEn": "What regulatory requirements apply, and how have they been translated into operational controls?",
    "evidenceRequired": "Compliance register, policies, control mapping",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27701 | NDMO | PDPL",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q063",
    "number": 63,
    "domainId": 10,
    "domainEn": "Compliance, Privacy & Data Security",
    "domainAr": "الامتثال والخصوصية وأمن البيانات",
    "questionAr": "كيف يتم تحديد البيانات الشخصية وإدارة الموافقات والحقوق والاحتفاظ؟",
    "questionEn": "How is personal data identified, and how are consent, rights, retention and sharing managed?",
    "evidenceRequired": "Privacy notices, consent records, DPIA, retention policy",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27701 | ISO/IEC 27018",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q064",
    "number": 64,
    "domainId": 10,
    "domainEn": "Compliance, Privacy & Data Security",
    "domainAr": "الامتثال والخصوصية وأمن البيانات",
    "questionAr": "هل توجد آلية اعتماد لمشاركة البيانات مع جهات داخلية أو خارجية؟",
    "questionEn": "Is there a formal approval mechanism and agreements for internal and external data sharing?",
    "evidenceRequired": "Data sharing agreements, approval workflow, audit trail",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 38505-1 | ISO/IEC 27701",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q065",
    "number": 65,
    "domainId": 10,
    "domainEn": "Compliance, Privacy & Data Security",
    "domainAr": "الامتثال والخصوصية وأمن البيانات",
    "questionAr": "هل توجد ضوابط أمنية تشمل التشفير والسجلات والمراقبة وإدارة الثغرات؟",
    "questionEn": "Are security controls in place covering encryption, logging, monitoring and vulnerability management?",
    "evidenceRequired": "ISMS controls, access reviews, encryption evidence, audit logs",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | ISO/IEC 27017",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q066",
    "number": 66,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "هل يمكن حصر جميع مصادر البيانات وتصنيفها حسب المصدر والنظام والمالك؟",
    "questionEn": "Can all data sources be inventoried and classified by source, system and ownership?",
    "evidenceRequired": "Full source inventory, architecture map, owner register",
    "evidenceAvailable": "",
    "isoReference": "TOGAF | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q067",
    "number": 67,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "كم عدد الأنظمة أو قواعد البيانات التي تعتبر مصادر رسمية معتمدة؟",
    "questionEn": "How many systems or databases are considered certified, official data sources?",
    "evidenceRequired": "Formal source inventory, source classification",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q068",
    "number": 68,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "ما نسبة البيانات المنتجة داخلياً مقابل البيانات المستهلكة من جهات خارجية؟",
    "questionEn": "What is the ratio of internally produced data vs data consumed from external sources?",
    "evidenceRequired": "Data source analysis, internal vs external mapping",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO/IEC 19944",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q069",
    "number": 69,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "هل يتم تبادل البيانات مع وزارة العدل أو جهات حكومية أخرى؟",
    "questionEn": "Is data exchanged with the Ministry of Justice or other government entities?",
    "evidenceRequired": "Exchange agreements, integration documents, communication protocols",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 19944 | NDMO",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q070",
    "number": 70,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "ما مصادر البيانات الحرجة التي سيؤثر توقفها على العمليات اليومية؟",
    "questionEn": "What are the critical data sources whose failure would immediately impact daily operations?",
    "evidenceRequired": "Critical sources list, impact assessment, continuity plans",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 27001 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q071",
    "number": 71,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "هل توجد بيانات يتم جمعها لكنها لا تُستخدم ويمكن استثمارها لخلق قيمة؟",
    "questionEn": "Is data being collected but not used or analysed — potential untapped value?",
    "evidenceRequired": "Data value assessment, gap analysis, unused data inventory",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | ISO/IEC 38505-1",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q072",
    "number": 72,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "كيف تنتقل البيانات بين الأنظمة: API أم تكامل آلي أم ملفات أم بريد إلكتروني؟",
    "questionEn": "How does data move between systems — API, automated integration, files or email?",
    "evidenceRequired": "Data flow diagrams, transfer mechanism documentation",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 19944 | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q073",
    "number": 73,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "ما تكرار تحديث البيانات عبر الأنظمة: لحظي أم يومي أم أسبوعي؟",
    "questionEn": "How frequently is data refreshed across systems — real-time, daily, weekly or monthly?",
    "evidenceRequired": "Data refresh policy, automated job schedules",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q074",
    "number": 74,
    "domainId": 11,
    "domainEn": "Data Sources & Data Flows",
    "domainAr": "مصادر البيانات وتدفقاتها",
    "questionAr": "ما العمليات التي تعتمد على الإدخال اليدوي؟ وما حجم مخاطره على الجودة؟",
    "questionEn": "What processes depend on manual data entry, and what quality risks does this create?",
    "evidenceRequired": "Process maps, operational risk assessment, manual error rates",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | ISO 8000-150",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q075",
    "number": 75,
    "domainId": 12,
    "domainEn": "Training Data & Organisational Impact",
    "domainAr": "ربط بيانات التدريب بالأثر المؤسسي",
    "questionAr": "هل يمكن ربط بيانات التدريب بنتائج الأداء الوظيفي وجودة العمل؟",
    "questionEn": "Can training data be linked to job performance outcomes and work quality?",
    "evidenceRequired": "Training impact reports, impact measurement models",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q076",
    "number": 76,
    "domainId": 12,
    "domainEn": "Training Data & Organisational Impact",
    "domainAr": "ربط بيانات التدريب بالأثر المؤسسي",
    "questionAr": "من هم أكبر مستهلكي البيانات؟ وما أنواع البيانات التي يحتاجونها؟",
    "questionEn": "Who are the biggest data consumers, and what types of data do they primarily need?",
    "evidenceRequired": "Consumers list, usage pattern analysis, frequent data requests",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q077",
    "number": 77,
    "domainId": 12,
    "domainEn": "Training Data & Organisational Impact",
    "domainAr": "ربط بيانات التدريب بالأثر المؤسسي",
    "questionAr": "ما أهم القرارات التي تعتمد على البيانات ولا يمكن اتخاذها في غيابها؟",
    "questionEn": "What are the most critical decisions that depend on data and cannot be made without it?",
    "evidenceRequired": "Data-dependent decision register, dependency analysis",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | ISO/IEC 38505-1",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q078",
    "number": 78,
    "domainId": 12,
    "domainEn": "Training Data & Organisational Impact",
    "domainAr": "ربط بيانات التدريب بالأثر المؤسسي",
    "questionAr": "هل يمكن تتبع رحلة المتدرب بالكامل من التسجيل إلى قياس الأثر الوظيفي؟",
    "questionEn": "Can the full trainee journey be tracked from registration through to measuring job impact?",
    "evidenceRequired": "Full trainee journey reports, impact tracking system",
    "evidenceAvailable": "",
    "isoReference": "DAMA-DMBOK — Journey Analytics",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q079",
    "number": 79,
    "domainId": 12,
    "domainEn": "Training Data & Organisational Impact",
    "domainAr": "ربط بيانات التدريب بالأثر المؤسسي",
    "questionAr": "ما نسبة البيانات المنظمة مقابل غير المنظمة؟ وكيف تتعاملون مع البيانات غير المنظمة؟",
    "questionEn": "What is the ratio of structured to unstructured data, and how is unstructured data handled?",
    "evidenceRequired": "Data structure assessment, structured vs unstructured classification",
    "evidenceAvailable": "",
    "isoReference": "TOGAF | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q080",
    "number": 80,
    "domainId": 13,
    "domainEn": "Execution, Roadmap & Value Measurement",
    "domainAr": "التنفيذ وخارطة الطريق وقياس الأثر",
    "questionAr": "هل توجد خارطة طريق لمبادرات البيانات بأولويات وموارد وميزانية ومخرجات واضحة؟",
    "questionEn": "Is there a data initiatives roadmap with defined phases, priorities, resources and deliverables?",
    "evidenceRequired": "Roadmap, milestones, budget, owners",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | TOGAF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q081",
    "number": 81,
    "domainId": 13,
    "domainEn": "Execution, Roadmap & Value Measurement",
    "domainAr": "التنفيذ وخارطة الطريق وقياس الأثر",
    "questionAr": "ما أهم مخاطر تنفيذ استراتيجية البيانات؟ وكيف يتم تتبعها ومعالجتها؟",
    "questionEn": "What are the key risks to the data strategy, and how are they tracked and mitigated?",
    "evidenceRequired": "Risk register, dependencies, mitigation plans",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | ISO/IEC 23894",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q082",
    "number": 82,
    "domainId": 13,
    "domainEn": "Execution, Roadmap & Value Measurement",
    "domainAr": "التنفيذ وخارطة الطريق وقياس الأثر",
    "questionAr": "كيف يتم ضمان تبني الإدارات لاستخدام البيانات الجديدة والسياسات المحدّثة؟",
    "questionEn": "How is adoption of new data assets, dashboards and policies ensured across business units?",
    "evidenceRequired": "Change management plan, adoption metrics, training, champions",
    "evidenceAvailable": "",
    "isoReference": "COBIT 2019 | DAMA-DMBOK",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q083",
    "number": 83,
    "domainId": 13,
    "domainEn": "Execution, Roadmap & Value Measurement",
    "domainAr": "التنفيذ وخارطة الطريق وقياس الأثر",
    "questionAr": "ما تعريف نجاح برنامج البيانات: إنجاز تقني، جودة، قرارات أفضل، أم نتائج مؤسسية؟",
    "questionEn": "How is data programme success defined — technical delivery, quality, better decisions or measurable outcomes?",
    "evidenceRequired": "Benefits map, KPIs, performance reports",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 38505-1 | COBIT 2019",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  },
  {
    "id": "q084",
    "number": 84,
    "domainId": 13,
    "domainEn": "Execution, Roadmap & Value Measurement",
    "domainAr": "التنفيذ وخارطة الطريق وقياس الأثر",
    "questionAr": "هل البيانات الحالية كافية من حيث الجودة والحداثة والحوكمة لبناء ذكاء اصطناعي اليوم؟",
    "questionEn": "Are current data assets sufficient in quality, timeliness, governance and compliance to support AI today?",
    "evidenceRequired": "AI data readiness assessment, readiness score, gap analysis",
    "evidenceAvailable": "",
    "isoReference": "ISO/IEC 25012 | ISO/IEC 42001 | NIST AI RMF",
    "score": null,
    "target": 4,
    "gap": null,
    "priority": "",
    "notes": "",
    "actionPlan": ""
  }
] satisfies DataAiDiagnosticQuestion[];

export const dataAiReportPrompts = [
  {
    "title": "Prompt 1: Gap Prioritisation",
    "prompt": "Copy columns A–L into your AI prompt and ask: \"Rank the top 10 gaps by strategic importance. Consider domain criticality, gap size, and the organisation's stated AI ambition.\""
  },
  {
    "title": "Prompt 2: Maturity Narrative",
    "prompt": "Ask: \"Based on these maturity scores, write a 3-paragraph executive summary of the organisation's data capability. Highlight strengths, critical gaps, and recommended first 90 days.\""
  },
  {
    "title": "Prompt 3: Roadmap Generation",
    "prompt": "Ask: \"Generate a phased 18-month data capability improvement roadmap. Prioritise domains with Gap ≥ 2 and align to ISO/IEC 38505-1, DAMA-DMBOK, and NDMO requirements.\""
  },
  {
    "title": "Prompt 4: AI Readiness Assessment",
    "prompt": "Filter rows where Domain = AI (ID 7) and ask: \"Given these data readiness scores, which AI use cases are feasible today, which require 6-month preparation, and which require 12+ months?\""
  },
  {
    "title": "Prompt 5: Risk Report",
    "prompt": "Ask: \"For all questions scoring 0 or 1, generate a risk table with: Risk Title, Likelihood, Impact, ISO Control Reference, and Recommended Mitigation.\""
  }
] satisfies DataAiReportPrompt[];
