export type HealthcareKpiLevel = "L1" | "L2" | "L3" | "L4" | "L5" | "L6" | "L7";

export type HealthcareKpi = {
  id: string;
  name: string;
  arabicName: string;
  level: HealthcareKpiLevel;
  item: number;
  type: string;
  category: string;
  family: string;
  owner: string;
  department: string;
  objective: string;
  unit: string;
  formula: string;
  source: string;
  refresh: string;
  target: string;
  definition: string;
  purpose: string;
  criticality: string;
  aiOpportunity: string;
};

export type HealthcareDashboardPack = {
  id: string;
  title: string;
  audience: string;
  purpose: string;
  levels: HealthcareKpiLevel[];
  families: string[];
  categories: string[];
  kpiCount: number;
  refresh: string;
};

export type ExecutiveLens = {
  id: string;
  title: string;
  role: string;
  mandate: string;
  boardQuestion: string;
  dashboardPackIds: string[];
  kpiIds: string[];
};

export type HealthcareCockpitDashboardPack = {
  id: string;
  title: string;
  audience: string;
  operatingQuestion: string;
  demoNarrative: string;
  families: string[];
  kpiIds: string[];
  lensIds: string[];
};

export type HospitalIntelligenceDomain = {
  id: string;
  title: string;
  description: string;
  packIds: string[];
  signal: string;
};

export type PredictiveOpportunity = {
  id: string;
  title: string;
  kpiId: string;
  area: string;
  valueCase: string;
  readiness: "High" | "Medium" | "Emerging";
  guardrail: string;
};

export const healthcareKpiLevels = [
  {
    "level": "L1",
    "worksheet": "L1",
    "label": "Enterprise Strategy, Governance and ED Command",
    "focus": "Strategic execution, accreditation, enterprise risk, executive decisions, and emergency department command KPIs.",
    "examples": [
      "Strategic KPI Achievement Rate",
      "Enterprise Transformation Milestone Completion Rate",
      "Accreditation Readiness Score"
    ]
  },
  {
    "level": "L2",
    "worksheet": "L2",
    "label": "Digital Health, Interoperability and AI",
    "focus": "EMR adoption, clinical documentation, NPHIES, integration, BI availability, data quality, cybersecurity, and predictive command-center operations.",
    "examples": [
      "EMR Adoption & Utilization Rate",
      "Clinical Documentation Completion Rate",
      "Order Entry Electronic Utilization Rate (CPOE)"
    ]
  },
  {
    "level": "L3",
    "worksheet": "L3",
    "label": "Patient Access, Identity and Engagement",
    "focus": "Registration, MRN quality, appointments, referrals, insurance authorization, care coordination, satisfaction, and telemedicine.",
    "examples": [
      "Patient Registration Turnaround Time",
      "Duplicate MRN Rate",
      "Appointment No-Show Rate"
    ]
  },
  {
    "level": "L4",
    "worksheet": "L4",
    "label": "Clinical Operations and Capacity",
    "focus": "Emergency operations, ICU, inpatient beds, discharge flow, maternity, pediatrics, IVF, and operating room utilization.",
    "examples": [
      "Emergency Department Door-to-Doctor Time",
      "Emergency Department Length of Stay",
      "ICU Occupancy Rate"
    ]
  },
  {
    "level": "L5",
    "worksheet": "L5",
    "label": "Diagnostics, Pharmacy and Infection Control",
    "focus": "Laboratory, radiology, cath lab, endoscopy, medication safety, pharmacy availability, rehabilitation, and HAI performance.",
    "examples": [
      "Laboratory Turnaround Time (TAT)",
      "Critical Lab Result Notification Compliance",
      "Radiology Report Turnaround Time"
    ]
  },
  {
    "level": "L6",
    "worksheet": "L6",
    "label": "Revenue, Finance and Enterprise Assets",
    "focus": "HIM coding, DNFB, collections, denials, payer settlement, margin, cost, supply chain, biomedical uptime, and facilities resilience.",
    "examples": [
      "Clinical Documentation Coding Accuracy Rate",
      "Discharged Not Final Billed (DNFB) Rate",
      "Net Collection Rate"
    ]
  },
  {
    "level": "L7",
    "worksheet": "L7",
    "label": "Workforce, Academic Medicine and Research",
    "focus": "Vacancy, productivity, turnover, nursing staffing and competency, overtime, residency, simulation, publications, and trials.",
    "examples": [
      "Workforce Vacancy Rate",
      "Workforce Productivity Index",
      "Employee Turnover Rate"
    ]
  }
] satisfies Array<{
  level: HealthcareKpiLevel;
  label: string;
  focus: string;
  worksheet: string;
  examples: string[];
}>;

export const healthcareDashboardPacks = [
  {
    "id": "enterprise-command",
    "title": "Enterprise Command and Governance",
    "audience": "CEO, COO, CMO, Quality, Risk",
    "purpose": "Track strategic execution, accreditation readiness, risk closure, executive decision flow, and enterprise emergency pressure.",
    "levels": [
      "L1"
    ],
    "families": [
      "F1 / G1 Enterprise Strategy & Planning",
      "F1 / G2 Governance, Risk & Compliance",
      "F1 / G3 Enterprise Performance, PMO & Value Realization",
      "F4 / G13 Emergency Department Operations"
    ],
    "refresh": "Real-time to monthly",
    "categories": [
      "Clinical Operations",
      "Clinical Quality",
      "Compliance",
      "Governance",
      "Operational",
      "Operational Governance",
      "Strategic"
    ],
    "kpiCount": 12
  },
  {
    "id": "digital-health-command",
    "title": "Digital Health and Predictive Command Center",
    "audience": "CIO, CMIO, CISO, CDO, Command Center",
    "purpose": "Operate EMR adoption, integration reliability, NPHIES continuity, BI availability, data quality, cybersecurity, and AI forecast accuracy.",
    "levels": [
      "L2"
    ],
    "families": [
      "F2 / G4 HIS, EMR & Clinical Platforms",
      "F2 / G5 Integration, Interoperability & NPHIES",
      "F2 / G6 Enterprise Data, BI & Analytics",
      "F2 / G7 Cybersecurity, Privacy & Data Protection",
      "F2 / G8 AI, Predictive Intelligence & Automation",
      "F14 / G51-G53 Enterprise Command Center & Predictive Operations"
    ],
    "refresh": "Real-time to daily",
    "categories": [
      "Analytics",
      "Clinical Informatics",
      "Cybersecurity",
      "Data Governance",
      "Digital Health",
      "Executive Operations Intelligence",
      "Integration",
      "Interoperability",
      "Predictive Analytics"
    ],
    "kpiCount": 10
  },
  {
    "id": "patient-access",
    "title": "Patient Access and Experience",
    "audience": "COO, Front Office, Scheduling, Patient Experience",
    "purpose": "Manage access friction from registration through referral, authorization, satisfaction, and digital engagement.",
    "levels": [
      "L3"
    ],
    "families": [
      "F3 / G9 Patient Registration & Identity Management",
      "F3 / G10 Appointment, Referral & Scheduling Management",
      "F3 / G11 Insurance Eligibility & Authorization",
      "F3 / G12 Care Coordination & Patient Navigation",
      "F9 / G34 Patient Experience & Satisfaction Management",
      "F9 / G35 Digital Patient Engagement & Telehealth"
    ],
    "refresh": "Daily and real-time",
    "categories": [
      "Access Management",
      "Care Coordination",
      "Data Quality",
      "Digital Engagement",
      "Financial Access",
      "Operational",
      "Patient Experience"
    ],
    "kpiCount": 10
  },
  {
    "id": "clinical-operations",
    "title": "Clinical Operations and Capacity",
    "audience": "COO, CMO, ED, ICU, Women Health, Surgery",
    "purpose": "Monitor acute flow, bed capacity, discharge discipline, specialty operations, maternal and pediatric pathways, and OR utilization.",
    "levels": [
      "L4"
    ],
    "families": [
      "F4 / G13 Emergency Department Operations",
      "F4 / G14 Critical Care & Intensive Care Operations",
      "F4 / G15 Inpatient & Bed Management Operations",
      "F4 / G16 Patient Flow, Transfer & Discharge Operations",
      "F5 / G17 Maternal & Obstetrics Services",
      "F5 / G18 Neonatal, NICU & Pediatric Services",
      "F5 / G19 Women Wellness, IVF & Preventive Care",
      "F6 / G22 Surgical & Operating Room Services"
    ],
    "refresh": "Hourly to daily",
    "categories": [
      "Clinical Operations",
      "Clinical Quality",
      "Critical Care",
      "Operational",
      "Operational Flow",
      "Pediatric Care",
      "Specialized Care",
      "Surgical Operations",
      "Women Health"
    ],
    "kpiCount": 15
  },
  {
    "id": "diagnostics-therapeutics",
    "title": "Diagnostics, Therapeutics and Safety",
    "audience": "Lab, Radiology, Pharmacy, Infection Control, Clinical Governance",
    "purpose": "Coordinate diagnostic turnaround, critical notifications, procedure quality, medication safety, pharmacy availability, rehab outcomes, and infection control.",
    "levels": [
      "L5"
    ],
    "families": [
      "F7 / G25 Laboratory & Blood Bank Services",
      "F7 / G26 Radiology, Imaging & Diagnostic Services",
      "F7 / G27 Cath Lab, Endoscopy & Interventional Services",
      "F7 / G28 Pharmacy & Medication Management",
      "F7 / G29 Rehabilitation, Physiotherapy & Therapeutic Services",
      "F8 / G32 Infection Prevention & Control"
    ],
    "refresh": "Real-time to monthly",
    "categories": [
      "Clinical Outcomes",
      "Diagnostics Operations",
      "Infection Control",
      "Operational",
      "Patient Safety"
    ],
    "kpiCount": 10
  },
  {
    "id": "finance-assets",
    "title": "Revenue, Finance and Enterprise Assets",
    "audience": "CFO, Revenue Cycle, Supply Chain, Biomedical, Facilities",
    "purpose": "Connect coding, billing, claims, collections, margin, cost, inventory, medical equipment, and utilities into one executive operating view.",
    "levels": [
      "L6"
    ],
    "families": [
      "F10 / G37 Health Information Management, Coding & Medical Records",
      "F10 / G38 Revenue Cycle & Billing Operations",
      "F10 / G39 Claims, Payer & Insurance Management",
      "F10 / G40 Financial Planning, Costing & Profitability",
      "F12 / G45 Supply Chain & Materials Management",
      "F12 / G46 Biomedical Engineering & Medical Equipment",
      "F12 / G47 Facility Operations, Safety & Environmental Services"
    ],
    "refresh": "Daily to monthly",
    "categories": [
      "Biomedical Engineering",
      "Cost Management",
      "Facility Operations",
      "Financial",
      "Financial Performance",
      "Health Information Management",
      "Insurance & Claims",
      "Insurance Operations",
      "Revenue Cycle",
      "Supply Chain"
    ],
    "kpiCount": 10
  },
  {
    "id": "workforce-academic-research",
    "title": "Workforce, Academic Medicine and Research",
    "audience": "CHRO, CNO, Academic Affairs, Research Leadership",
    "purpose": "Balance workforce sufficiency, productivity, nursing coverage, academic utilization, simulation capacity, research output, and clinical trial enrollment.",
    "levels": [
      "L7"
    ],
    "families": [
      "F11 / G41 Workforce, Staffing & Productivity Management",
      "F11 / G42 Nursing Operations & Clinical Workforce Excellence",
      "F11 / G43 Academic Medicine, Residency & Simulation Programs",
      "F11 / G44 Research, Innovation & Clinical Trials"
    ],
    "refresh": "Daily to quarterly",
    "categories": [
      "Academic Medicine",
      "Clinical Workforce",
      "Nursing Operations",
      "Research & Innovation",
      "Research Operations",
      "Workforce Management",
      "Workforce Operations"
    ],
    "kpiCount": 10
  }
] satisfies HealthcareDashboardPack[];

export const healthcareKpis = [
  {
    "id": "hospital-l1-01",
    "name": "Strategic KPI Achievement Rate",
    "arabicName": "معدل تحقيق مؤشرات الأداء الاستراتيجية",
    "level": "L1",
    "item": 1,
    "type": "Strategic",
    "category": "Lagging",
    "family": "F1 / G1 Enterprise Strategy & Planning",
    "owner": "CEO",
    "department": "Strategy Office / PMO",
    "objective": "Measure enterprise strategy execution effectiveness",
    "unit": "%",
    "formula": "Achieved KPIs ÷ Total KPIs × 100",
    "source": "PMO Platform / BI",
    "refresh": "Monthly",
    "target": ">90%",
    "definition": "Measures the percentage of strategic enterprise KPIs achieved successfully against the total approved strategic KPIs within the defined period.",
    "purpose": "Ensure Hospital Name is successfully executing its strategic plan, Vision 2030 objectives, transformation roadmap, and institutional priorities.",
    "criticality": "Ensures Hospital Name strategic transformation execution and Vision 2030 alignment",
    "aiOpportunity": "Predict KPI underperformance risk"
  },
  {
    "id": "hospital-l1-02",
    "name": "Enterprise Transformation Milestone Completion Rate",
    "arabicName": "معدل إنجاز مراحل التحول المؤسسي",
    "level": "L1",
    "item": 2,
    "type": "Strategic",
    "category": "Leading",
    "family": "F1 / G1 Enterprise Strategy & Planning",
    "owner": "CEO / CIO",
    "department": "PMO / Transformation Office",
    "objective": "Monitor execution of strategic initiatives",
    "unit": "%",
    "formula": "Completed milestones ÷ Planned milestones × 100",
    "source": "PMO / Project Systems",
    "refresh": "Weekly",
    "target": ">95%",
    "definition": "Measures the percentage of completed transformation-program milestones compared to planned milestones across strategic initiatives and enterprise projects.",
    "purpose": "Monitor execution progress of digital transformation, operational modernization, AI initiatives, and enterprise strategic programs.",
    "criticality": "Critical for digital-health and academic-medical-center transformation programs",
    "aiOpportunity": "Forecast project delays"
  },
  {
    "id": "hospital-l1-03",
    "name": "Accreditation Readiness Score",
    "arabicName": "درجة الجاهزية للاعتماد",
    "level": "L1",
    "item": 3,
    "type": "Compliance",
    "category": "Leading",
    "family": "F1 / G2 Governance, Risk & Compliance",
    "owner": "CEO / Quality Director",
    "department": "Quality / Compliance",
    "objective": "Maintain JCIA & CBAHI readiness",
    "unit": "%",
    "formula": "Passed standards ÷ Total standards × 100",
    "source": "Quality Mgmt System",
    "refresh": "Weekly",
    "target": ">95%",
    "definition": "Measures the organization’s readiness level against accreditation standards such as JCIA and CBAHI based on audits, compliance checks, and evidence completion.",
    "purpose": "Ensure continuous accreditation readiness, regulatory compliance, patient safety, and institutional quality excellence.",
    "criticality": "Directly impacts hospital accreditation and reputation",
    "aiOpportunity": "Predict compliance gaps"
  },
  {
    "id": "hospital-l1-04",
    "name": "Enterprise Risk Closure Rate",
    "arabicName": "معدل إغلاق المخاطر المؤسسية",
    "level": "L1",
    "item": 4,
    "type": "Governance",
    "category": "Leading",
    "family": "F1 / G2 Governance, Risk & Compliance",
    "owner": "CRO / CEO",
    "department": "Risk Management",
    "objective": "Reduce unresolved enterprise risks",
    "unit": "%",
    "formula": "Closed risks ÷ Total identified risks × 100",
    "source": "GRC Platform",
    "refresh": "Weekly",
    "target": ">90%",
    "definition": "Measures the percentage of identified enterprise risks that were mitigated or formally closed within the defined timeframe.",
    "purpose": "Reduce operational, financial, clinical, cybersecurity, and compliance risks affecting hospital operations and patient care.",
    "criticality": "Important for operational resilience and patient safety governance",
    "aiOpportunity": "Predict high-risk operational areas"
  },
  {
    "id": "hospital-l1-05",
    "name": "Executive Decision Turnaround Time",
    "arabicName": "زمن اتخاذ القرار التنفيذي",
    "level": "L1",
    "item": 5,
    "type": "Operational Governance",
    "category": "Leading",
    "family": "F1 / G3 Enterprise Performance, PMO & Value Realization",
    "owner": "CEO Office",
    "department": "Administration / PMO",
    "objective": "Accelerate executive decisions and governance responsiveness",
    "unit": "Days",
    "formula": "Avg approval date − request date",
    "source": "Workflow / BPM System",
    "refresh": "Weekly",
    "target": "<3 days",
    "definition": "Measures the average time required for executive leadership to review, approve, or reject operational and strategic decisions.",
    "purpose": "Improve executive responsiveness, governance agility, escalation management, and institutional decision-making efficiency.",
    "criticality": "Improves responsiveness across hospital operations",
    "aiOpportunity": "Predict delayed executive approvals"
  },
  {
    "id": "hospital-l1-06",
    "name": "Emergency Department Door-to-Doctor Time",
    "arabicName": "زمن الوصول من باب الطوارئ إلى الطبيب",
    "level": "L1",
    "item": 6,
    "type": "Clinical Operations",
    "category": "Real-Time",
    "family": "F4 / G13 Emergency Department Operations",
    "owner": "COO / ED Director",
    "department": "Emergency Department",
    "objective": "Improve emergency access and throughput",
    "unit": "Minutes",
    "formula": "Avg physician first-contact time − patient arrival time",
    "source": "ED System / HIS",
    "refresh": "Real-Time",
    "target": "<15 min",
    "definition": "Measures the average time between patient arrival to the Emergency Department and the first physician assessment.",
    "purpose": "Improve emergency responsiveness, reduce patient waiting, enhance patient safety, and optimize ED throughput.",
    "criticality": "executive visibility dependendency",
    "aiOpportunity": "Predict ED congestion and overload"
  },
  {
    "id": "hospital-l1-07",
    "name": "Emergency Department Length of Stay",
    "arabicName": "مدة إقامة المريض في قسم الطوارئ",
    "level": "L1",
    "item": 7,
    "type": "Clinical Operations",
    "category": "Real-Time",
    "family": "F4 / G13 Emergency Department Operations",
    "owner": "COO / ED Director",
    "department": "Emergency Department",
    "objective": "Reduce ED overcrowding and boarding",
    "unit": "Hours",
    "formula": "Avg discharge/admission time − arrival time",
    "source": "ED System / HIS",
    "refresh": "Hourly",
    "target": "<4 hrs",
    "definition": "Measures the average total time patients spend in the Emergency Department from arrival until discharge, admission, or transfer.",
    "purpose": "Reduce ED overcrowding, boarding delays, and improve patient flow and operational efficiency.",
    "criticality": "Directly impacts patient flow and satisfaction",
    "aiOpportunity": "Predict prolonged ED stay"
  },
  {
    "id": "hospital-l1-08",
    "name": "Emergency Department Left Without Being Seen Rate",
    "arabicName": "معدل مغادرة المرضى من الطوارئ قبل المعاينة",
    "level": "L1",
    "item": 8,
    "type": "Clinical Quality",
    "category": "Lagging",
    "family": "F4 / G13 Emergency Department Operations",
    "owner": "CMO / ED Director",
    "department": "Emergency Department",
    "objective": "Reduce patient leakage and access failures",
    "unit": "%",
    "formula": "LWBS patients ÷ Total ED visits × 100",
    "source": "ED System",
    "refresh": "Daily",
    "target": "<2%",
    "definition": "Measures the percentage of patients who leave the Emergency Department before being evaluated by a physician or clinician.",
    "purpose": "Identify access issues, overcrowding problems, and patient dissatisfaction affecting emergency-care quality.",
    "criticality": "Reflects ED efficiency and patient trust",
    "aiOpportunity": "Predict patient abandonment risk"
  },
  {
    "id": "hospital-l1-09",
    "name": "Ambulance Handover Delay Rate",
    "arabicName": "معدل تأخر تسليم مرضى الإسعاف",
    "level": "L1",
    "item": 9,
    "type": "Operational",
    "category": "Leading",
    "family": "F4 / G13 Emergency Department Operations",
    "owner": "COO",
    "department": "ED / Ambulance Services",
    "objective": "Reduce ambulance bottlenecks and transfer delays",
    "unit": "%",
    "formula": "Delayed handovers ÷ Total ambulance arrivals × 100",
    "source": "EMS / ED Systems",
    "refresh": "Real-Time",
    "target": "<5%",
    "definition": "Measures the percentage of ambulance arrivals experiencing delays in transferring patients to Emergency Department clinical teams.",
    "purpose": "Improve emergency intake efficiency, reduce ambulance waiting times, and enhance critical-care readiness.",
    "criticality": "Critical for emergency readiness and throughput",
    "aiOpportunity": "Predict ambulance queue buildup"
  },
  {
    "id": "hospital-l1-10",
    "name": "Emergency Department Capacity Utilization Rate",
    "arabicName": "معدل استغلال الطاقة الاستيعابية لقسم الطوارئ",
    "level": "L1",
    "item": 10,
    "type": "Operational",
    "category": "Real-Time",
    "family": "F4 / G13 Emergency Department Operations",
    "owner": "COO / ED Director",
    "department": "Emergency Department",
    "objective": "Optimize ED capacity and operational readiness",
    "unit": "%",
    "formula": "Occupied ED beds ÷ Total ED beds × 100",
    "source": "HIS / Bed Mgmt",
    "refresh": "Real-Time",
    "target": "80–85%",
    "definition": "Measures the percentage of occupied Emergency Department beds or treatment spaces relative to total available ED capacity.",
    "purpose": "Optimize ED operational capacity, support surge planning, reduce overcrowding, and improve command-center visibility.",
    "criticality": "Operational intelligence model",
    "aiOpportunity": "Predict ED saturation and surge demand"
  },
  {
    "id": "hospital-l2-01",
    "name": "EMR Adoption & Utilization Rate",
    "arabicName": "معدل استخدام وتبني السجل الطبي الإلكتروني",
    "level": "L2",
    "item": 1,
    "type": "Digital Health",
    "category": "Leading",
    "family": "F2 / G4 HIS, EMR & Clinical Platforms",
    "owner": "CIO / CMIO",
    "department": "IT / Clinical Informatics",
    "objective": "Maximize enterprise EMR utilization and digital clinical workflows",
    "unit": "%",
    "formula": "Active EMR users ÷ Total intended users × 100",
    "source": "EMR / IAM",
    "refresh": "Daily",
    "target": ">95%",
    "definition": "Measures the percentage of clinicians and healthcare staff actively using the EMR system as part of their daily clinical workflows.",
    "purpose": "Ensure successful digital transformation, reduce paper-based processes, improve clinical efficiency, and standardize patient-care documentation.",
    "criticality": "Critical for digital transformation and clinical standardization at Hospital Name",
    "aiOpportunity": "Predict adoption gaps by department"
  },
  {
    "id": "hospital-l2-02",
    "name": "Clinical Documentation Completion Rate",
    "arabicName": "معدل اكتمال التوثيق السريري",
    "level": "L2",
    "item": 2,
    "type": "Clinical Informatics",
    "category": "Operational",
    "family": "F2 / G4 HIS, EMR & Clinical Platforms",
    "owner": "CMIO / CMO",
    "department": "Physicians / Nursing",
    "objective": "Ensure complete and timely clinical documentation",
    "unit": "%",
    "formula": "Completed charts ÷ Total charts × 100",
    "source": "EMR",
    "refresh": "Hourly",
    "target": ">98%",
    "definition": "Measures the percentage of patient clinical records and documentation completed accurately and on time according to hospital standards.",
    "purpose": "Improve patient safety, coding accuracy, revenue-cycle performance, legal compliance, and continuity of care.",
    "criticality": "Impacts quality, coding, revenue cycle and patient safety",
    "aiOpportunity": "Predict incomplete charts and delays"
  },
  {
    "id": "hospital-l2-03",
    "name": "Order Entry Electronic Utilization Rate (CPOE)",
    "arabicName": "معدل استخدام الإدخال الإلكتروني للأوامر الطبية",
    "level": "L2",
    "item": 3,
    "type": "Digital Health",
    "category": "Leading",
    "family": "F2 / G4 HIS, EMR & Clinical Platforms",
    "owner": "CIO / CMO",
    "department": "Clinical Informatics",
    "objective": "Reduce paper/manual clinical orders",
    "unit": "%",
    "formula": "Electronic orders ÷ Total orders × 100",
    "source": "EMR / CPOE",
    "refresh": "Daily",
    "target": ">95%",
    "definition": "Measures the percentage of medical orders entered electronically through the Computerized Physician Order Entry (CPOE) system instead of manual or paper methods.",
    "purpose": "Reduce medication errors, improve patient safety, accelerate order processing, and enhance clinical workflow automation.",
    "criticality": "Essential for patient safety and medication control",
    "aiOpportunity": "Detect manual-order risk patterns"
  },
  {
    "id": "hospital-l2-04",
    "name": "NPHIES Transaction Success Rate",
    "arabicName": "معدل نجاح معاملات نفيس",
    "level": "L2",
    "item": 4,
    "type": "Interoperability",
    "category": "Real-Time",
    "family": "F2 / G5 Integration, Interoperability & NPHIES",
    "owner": "CIO",
    "department": "Integration Team / Revenue Cycle",
    "objective": "Ensure uninterrupted payer and interoperability connectivity",
    "unit": "%",
    "formula": "Successful transactions ÷ Total transactions × 100",
    "source": "Integration Engine / NPHIES",
    "refresh": "Real-Time",
    "target": ">99%",
    "definition": "Measures the percentage of successful electronic transactions exchanged with the Saudi NPHIES platform without rejection or technical failure.",
    "purpose": "Ensure interoperability, insurance continuity, claims processing efficiency, and compliance with Saudi healthcare integration standards.",
    "criticality": "Critical for Saudi payer ecosystem and claims continuity",
    "aiOpportunity": "Predict transaction failures"
  },
  {
    "id": "hospital-l2-05",
    "name": "Interface Error Rate",
    "arabicName": "معدل أخطاء التكامل والواجهات",
    "level": "L2",
    "item": 5,
    "type": "Integration",
    "category": "Real-Time",
    "family": "F2 / G5 Integration, Interoperability & NPHIES",
    "owner": "CIO",
    "department": "Integration Team",
    "objective": "Reduce HL7/API integration failures",
    "unit": "%",
    "formula": "Failed interfaces ÷ Total interface transactions × 100",
    "source": "Integration Engine",
    "refresh": "Real-Time",
    "target": "<1%",
    "definition": "Measures the percentage of failed or erroneous system integration transactions across interfaces, APIs, HL7 connections, and interoperability channels.",
    "purpose": "Ensure stable integration between HIS, EMR, LIS, RIS, ERP, NPHIES, and external healthcare systems.",
    "criticality": "Directly impacts hospital operational continuity",
    "aiOpportunity": "Predict interface outages"
  },
  {
    "id": "hospital-l2-06",
    "name": "Executive Dashboard Availability Rate",
    "arabicName": "معدل توفر لوحات المعلومات التنفيذية",
    "level": "L2",
    "item": 6,
    "type": "Analytics",
    "category": "Real-Time",
    "family": "F2 / G6 Enterprise Data, BI & Analytics",
    "owner": "CIO / COO",
    "department": "BI Team",
    "objective": "Ensure executive command-center continuity",
    "unit": "%",
    "formula": "Dashboard uptime ÷ Total scheduled uptime × 100",
    "source": "BI Platform",
    "refresh": "Real-Time",
    "target": ">99.5%",
    "definition": "Measures the percentage of time executive dashboards, operational cockpits, and command-center visualizations remain available and accessible.",
    "purpose": "Ensure continuous executive visibility, operational monitoring, and command-center decision-making capability.",
    "criticality": "executive visibility dependendency",
    "aiOpportunity": "Predict dashboard failures"
  },
  {
    "id": "hospital-l2-07",
    "name": "Data Quality Compliance Score",
    "arabicName": "درجة جودة البيانات والامتثال",
    "level": "L2",
    "item": 7,
    "type": "Data Governance",
    "category": "Leading",
    "family": "F2 / G6 Enterprise Data, BI & Analytics",
    "owner": "CDO",
    "department": "Data Governance Office",
    "objective": "Improve enterprise healthcare data reliability",
    "unit": "%",
    "formula": "Valid records ÷ Total records × 100",
    "source": "DQ Platform / Data Warehouse",
    "refresh": "Daily",
    "target": ">95%",
    "definition": "Measures the quality, completeness, accuracy, consistency, and validity of enterprise healthcare data across operational and analytical systems.",
    "purpose": "Ensure reliable analytics, trustworthy KPIs, accurate reporting, AI-readiness, and executive decision support.",
    "criticality": "Reliable analytics required for command-center decisions",
    "aiOpportunity": "Detect anomalous data patterns"
  },
  {
    "id": "hospital-l2-08",
    "name": "Cybersecurity Incident Response Time",
    "arabicName": "زمن الاستجابة للحوادث السيبرانية",
    "level": "L2",
    "item": 8,
    "type": "Cybersecurity",
    "category": "Real-Time",
    "family": "F2 / G7 Cybersecurity, Privacy & Data Protection",
    "owner": "CISO",
    "department": "Cybersecurity Operations",
    "objective": "Accelerate incident containment and recovery",
    "unit": "Minutes",
    "formula": "Avg incident closure time − detection time",
    "source": "SIEM / SOC Platform",
    "refresh": "Real-Time",
    "target": "<30 min",
    "definition": "Measures the average time required to detect, respond to, contain, and resolve cybersecurity incidents affecting hospital systems and data.",
    "purpose": "Protect hospital operations, patient information, clinical systems, and institutional cybersecurity resilience.",
    "criticality": "Essential for healthcare cybersecurity resilience",
    "aiOpportunity": "Predict threat escalation"
  },
  {
    "id": "hospital-l2-09",
    "name": "Predictive Capacity Forecast Accuracy",
    "arabicName": "دقة التنبؤ بالسعة التشغيلية",
    "level": "L2",
    "item": 9,
    "type": "Predictive Analytics",
    "category": "Predictive",
    "family": "F2 / G8 AI, Predictive Intelligence & Automation",
    "owner": "COO / CIO",
    "department": "AI & Analytics Team",
    "objective": "Improve operational capacity forecasting",
    "unit": "%",
    "formula": "Accurate predictions ÷ Total predictions × 100",
    "source": "AI Platform / Data Warehouse",
    "refresh": "Daily",
    "target": ">90%",
    "definition": "Measures the accuracy of AI or analytics models in forecasting operational capacity such as beds, ICU occupancy, ED demand, and staffing needs.",
    "purpose": "Improve proactive operational planning, surge preparedness, and hospital resource optimization.",
    "criticality": "Critical for ICU, ED and bed planning at Hospital Name",
    "aiOpportunity": "Self-learning forecasting optimization"
  },
  {
    "id": "hospital-l2-10",
    "name": "Command Center Alert Resolution SLA Compliance",
    "arabicName": "معدل الالتزام بمعالجة تنبيهات مركز القيادة ضمن اتفاقية الخدمة",
    "level": "L2",
    "item": 10,
    "type": "Executive Operations Intelligence",
    "category": "Real-Time",
    "family": "F14 / G51-G53 Enterprise Command Center & Predictive Operations",
    "owner": "COO / Command Center Director",
    "department": "Command Center Operations",
    "objective": "Ensure rapid operational escalation handling",
    "unit": "%",
    "formula": "Alerts resolved within SLA ÷ Total alerts × 100",
    "source": "Command Center Platform",
    "refresh": "Real-Time",
    "target": ">95%",
    "definition": "Measures the percentage of command-center operational alerts resolved within the predefined SLA timeframe.",
    "purpose": "Ensure rapid escalation handling, operational responsiveness, bottleneck resolution, and enterprise operational control.",
    "criticality": "Operational intelligence model",
    "aiOpportunity": "Predict operational bottlenecks and escalations"
  },
  {
    "id": "hospital-l3-01",
    "name": "Patient Registration Turnaround Time",
    "arabicName": "زمن إنجاز تسجيل المريض",
    "level": "L3",
    "item": 1,
    "type": "Operational",
    "category": "Real-Time",
    "family": "F3 / G9 Patient Registration & Identity Management",
    "owner": "COO",
    "department": "Registration / Front Office",
    "objective": "Accelerate patient onboarding and reduce waiting",
    "unit": "Minutes",
    "formula": "Avg registration completion time − patient arrival time",
    "source": "HIS / Registration System",
    "refresh": "Real-Time",
    "target": "<10 min",
    "definition": "Measures the average time required to complete patient registration from arrival until successful registration in the hospital system.",
    "purpose": "Improve patient access efficiency, reduce waiting times, and accelerate patient onboarding into clinical services.",
    "criticality": "First patient touchpoint affecting experience and throughput",
    "aiOpportunity": "Predict registration bottlenecks"
  },
  {
    "id": "hospital-l3-02",
    "name": "Duplicate MRN Rate",
    "arabicName": "معدل تكرار الرقم الطبي للمريض",
    "level": "L3",
    "item": 2,
    "type": "Data Quality",
    "category": "Leading",
    "family": "F3 / G9 Patient Registration & Identity Management",
    "owner": "CIO / HIM Director",
    "department": "HIM / Registration",
    "objective": "Improve patient identity integrity and safety",
    "unit": "%",
    "formula": "Duplicate MRNs ÷ Total active MRNs × 100",
    "source": "HIS / MPI",
    "refresh": "Daily",
    "target": "<0.5%",
    "definition": "Measures the percentage of duplicate Medical Record Numbers (MRNs) created for the same patient within the hospital systems.",
    "purpose": "Improve patient identity accuracy, reduce clinical risk, enhance interoperability, and maintain data integrity.",
    "criticality": "Critical for patient safety, interoperability and analytics accuracy",
    "aiOpportunity": "AI duplicate-patient detection"
  },
  {
    "id": "hospital-l3-03",
    "name": "Appointment No-Show Rate",
    "arabicName": "معدل عدم حضور المواعيد",
    "level": "L3",
    "item": 3,
    "type": "Operational",
    "category": "Lagging",
    "family": "F3 / G10 Appointment, Referral & Scheduling Management",
    "owner": "COO",
    "department": "Scheduling / Clinics",
    "objective": "Reduce wasted clinic capacity",
    "unit": "%",
    "formula": "Missed appointments ÷ Total appointments × 100",
    "source": "Scheduling System",
    "refresh": "Daily",
    "target": "<5%",
    "definition": "Measures the percentage of scheduled patients who fail to attend their appointments without cancellation.",
    "purpose": "Optimize clinic utilization, reduce wasted capacity, improve scheduling efficiency, and increase patient access availability.",
    "criticality": "Directly impacts clinic utilization and patient access",
    "aiOpportunity": "Predict no-show likelihood"
  },
  {
    "id": "hospital-l3-04",
    "name": "First Available Appointment by Specialty",
    "arabicName": "أول موعد متاح حسب التخصص",
    "level": "L3",
    "item": 4,
    "type": "Access Management",
    "category": "Leading",
    "family": "F3 / G10 Appointment, Referral & Scheduling Management",
    "owner": "COO",
    "department": "Scheduling / Specialty Clinics",
    "objective": "Improve patient access to specialized care",
    "unit": "Days",
    "formula": "Avg days to next available appointment",
    "source": "Scheduling System",
    "refresh": "Daily",
    "target": "<7 days",
    "definition": "Measures the average waiting period until the next available appointment slot for each clinical specialty.",
    "purpose": "Improve patient access to specialty care, reduce waiting lists, and optimize outpatient scheduling capacity.",
    "criticality": "Critical for women’s health, pediatrics and specialty demand management",
    "aiOpportunity": "Predict specialty demand surges"
  },
  {
    "id": "hospital-l3-05",
    "name": "Referral Closure Rate",
    "arabicName": "معدل إغلاق الإحالات الطبية",
    "level": "L3",
    "item": 5,
    "type": "Care Coordination",
    "category": "Leading",
    "family": "F3 / G10 Appointment, Referral & Scheduling Management",
    "owner": "COO",
    "department": "Referral Management",
    "objective": "Improve referral continuity and care completion",
    "unit": "%",
    "formula": "Closed referrals ÷ Total referrals × 100",
    "source": "HIS / Referral Platform",
    "refresh": "Daily",
    "target": ">90%",
    "definition": "Measures the percentage of referrals successfully completed and closed within the defined care pathway.",
    "purpose": "Improve continuity of care, coordination between specialties, and patient journey completion.",
    "criticality": "Important for continuity across Hospital Name specialty ecosystem",
    "aiOpportunity": "Predict referral delays"
  },
  {
    "id": "hospital-l3-06",
    "name": "Insurance Eligibility Verification Success Rate",
    "arabicName": "معدل نجاح التحقق من أهلية التأمين",
    "level": "L3",
    "item": 6,
    "type": "Financial Access",
    "category": "Real-Time",
    "family": "F3 / G11 Insurance Eligibility & Authorization",
    "owner": "CFO / Revenue Cycle Director",
    "department": "Insurance / Front Office",
    "objective": "Ensure rapid financial clearance and payer validation",
    "unit": "%",
    "formula": "Successful eligibility checks ÷ Total eligibility checks × 100",
    "source": "NPHIES / HIS",
    "refresh": "Real-Time",
    "target": ">98%",
    "definition": "Measures the percentage of successful insurance eligibility verification transactions completed before service delivery.",
    "purpose": "Reduce claim denials, accelerate patient access, and ensure financial clearance before treatment.",
    "criticality": "executive visibility dependendency",
    "aiOpportunity": "Predict payer rejection risk"
  },
  {
    "id": "hospital-l3-07",
    "name": "Authorization Turnaround Time",
    "arabicName": "زمن إصدار الموافقات التأمينية",
    "level": "L3",
    "item": 7,
    "type": "Operational",
    "category": "Leading",
    "family": "F3 / G11 Insurance Eligibility & Authorization",
    "owner": "CFO",
    "department": "Insurance Authorization Team",
    "objective": "Accelerate approvals for clinical services",
    "unit": "Hours",
    "formula": "Avg authorization completion time",
    "source": "Authorization Platform / NPHIES",
    "refresh": "Hourly",
    "target": "<4 hrs",
    "definition": "Measures the average time required to obtain insurance authorization approvals for clinical procedures and services.",
    "purpose": "Reduce delays in treatment, diagnostics, admissions, and surgical scheduling caused by authorization bottlenecks.",
    "criticality": "Impacts surgery, diagnostics and admissions throughput",
    "aiOpportunity": "Predict authorization delays"
  },
  {
    "id": "hospital-l3-08",
    "name": "Care Coordination Escalation Rate",
    "arabicName": "معدل تصعيد حالات تنسيق الرعاية",
    "level": "L3",
    "item": 8,
    "type": "Care Coordination",
    "category": "Predictive",
    "family": "F3 / G12 Care Coordination & Patient Navigation",
    "owner": "COO",
    "department": "Case Management / Care Coordination",
    "objective": "Reduce patient journey delays and escalations",
    "unit": "%",
    "formula": "Escalated coordination cases ÷ Total cases × 100",
    "source": "Care Management Platform",
    "refresh": "Daily",
    "target": "<5%",
    "definition": "Measures the percentage of patient-care coordination cases requiring escalation due to delays, complexity, or operational issues.",
    "purpose": "Identify coordination inefficiencies, improve multidisciplinary collaboration, and reduce patient journey delays.",
    "criticality": "Important for complex maternal, pediatric and oncology care",
    "aiOpportunity": "Predict escalation probability"
  },
  {
    "id": "hospital-l3-09",
    "name": "Patient Satisfaction Score",
    "arabicName": "درجة رضا المرضى",
    "level": "L3",
    "item": 9,
    "type": "Patient Experience",
    "category": "Lagging",
    "family": "F9 / G34 Patient Experience & Satisfaction Management",
    "owner": "CEO / Patient Experience Director",
    "department": "Patient Experience",
    "objective": "Improve overall patient trust and institutional reputation",
    "unit": "Score / %",
    "formula": "Avg patient survey score",
    "source": "CRM / Survey Platform",
    "refresh": "Weekly",
    "target": ">4.5/5",
    "definition": "Measures the overall patient satisfaction level based on surveys and patient-experience feedback.",
    "purpose": "Improve patient experience, institutional reputation, quality perception, and service excellence.",
    "criticality": "Major executive KPI for Hospital Name reputation and service excellence",
    "aiOpportunity": "Sentiment and dissatisfaction prediction"
  },
  {
    "id": "hospital-l3-10",
    "name": "Telemedicine Utilization Rate",
    "arabicName": "معدل استخدام خدمات الطب الاتصالي",
    "level": "L3",
    "item": 10,
    "type": "Digital Engagement",
    "category": "Leading",
    "family": "F9 / G35 Digital Patient Engagement & Telehealth",
    "owner": "CIO / COO",
    "department": "Virtual Care Services",
    "objective": "Expand digital-health access and virtual care delivery",
    "unit": "%",
    "formula": "Virtual visits ÷ Total outpatient visits × 100",
    "source": "Telemedicine Platform",
    "refresh": "Daily",
    "target": ">25%",
    "definition": "Measures the percentage of outpatient consultations delivered through telemedicine and virtual-care channels.",
    "purpose": "Expand digital-health access, improve patient convenience, reduce physical visits, and support virtual-care strategy.",
    "criticality": "Operational intelligence model",
    "aiOpportunity": "Predict virtual-care demand patterns"
  },
  {
    "id": "hospital-l4-01",
    "name": "Emergency Department Door-to-Doctor Time",
    "arabicName": "زمن الوصول من باب الطوارئ إلى الطبيب",
    "level": "L4",
    "item": 1,
    "type": "Clinical Operations",
    "category": "Real-Time",
    "family": "F4 / G13 Emergency Department Operations",
    "owner": "COO / ED Director",
    "department": "Emergency Department",
    "objective": "Improve emergency responsiveness and patient throughput",
    "unit": "Minutes",
    "formula": "Avg physician first-contact time − patient arrival time",
    "source": "ED System / HIS",
    "refresh": "Real-Time",
    "target": "<15 min",
    "definition": "Measures the average time between patient arrival at the Emergency Department and the first physician assessment.",
    "purpose": "Improve emergency responsiveness, reduce waiting times, enhance patient safety, and optimize ED throughput.",
    "criticality": "One of the most critical operational KPIs for acute-care hospitals",
    "aiOpportunity": "Predict ED congestion and staffing needs"
  },
  {
    "id": "hospital-l4-02",
    "name": "Emergency Department Length of Stay",
    "arabicName": "مدة إقامة المريض في قسم الطوارئ",
    "level": "L4",
    "item": 2,
    "type": "Clinical Operations",
    "category": "Real-Time",
    "family": "F4 / G13 Emergency Department Operations",
    "owner": "COO",
    "department": "Emergency Department",
    "objective": "Reduce overcrowding and patient boarding",
    "unit": "Hours",
    "formula": "Avg ED discharge/admission time − arrival time",
    "source": "ED System",
    "refresh": "Hourly",
    "target": "<4 hrs",
    "definition": "Measures the average total time patients spend in the Emergency Department from arrival until discharge, admission, or transfer.",
    "purpose": "Reduce overcrowding, improve patient flow, minimize boarding delays, and increase operational efficiency.",
    "criticality": "Directly impacts patient flow, satisfaction and bed utilization",
    "aiOpportunity": "Predict prolonged ED stays"
  },
  {
    "id": "hospital-l4-03",
    "name": "ICU Occupancy Rate",
    "arabicName": "معدل إشغال العناية المركزة",
    "level": "L4",
    "item": 3,
    "type": "Critical Care",
    "category": "Real-Time",
    "family": "F4 / G14 Critical Care & Intensive Care Operations",
    "owner": "COO / ICU Director",
    "department": "ICU / Critical Care",
    "objective": "Optimize critical-care capacity management",
    "unit": "%",
    "formula": "Occupied ICU beds ÷ Total ICU beds × 100",
    "source": "HIS / Bed Mgmt",
    "refresh": "Hourly",
    "target": "80–85%",
    "definition": "Measures the percentage of occupied ICU beds compared to the total available ICU capacity during a defined period.",
    "purpose": "Optimize critical-care capacity, support surge planning, and ensure ICU readiness for severe cases.",
    "criticality": "Critical for tertiary-care and emergency readiness",
    "aiOpportunity": "Predict ICU saturation"
  },
  {
    "id": "hospital-l4-04",
    "name": "Average Length of Stay (ALOS)",
    "arabicName": "متوسط مدة إقامة المرضى",
    "level": "L4",
    "item": 4,
    "type": "Clinical Operations",
    "category": "Lagging",
    "family": "F4 / G15 Inpatient & Bed Management Operations",
    "owner": "CMO / COO",
    "department": "Inpatient Services",
    "objective": "Optimize inpatient throughput and reduce unnecessary LOS",
    "unit": "Days",
    "formula": "Total inpatient days ÷ Total discharges",
    "source": "EMR / HIS",
    "refresh": "Daily",
    "target": "Benchmark by specialty",
    "definition": "Measures the average number of days patients remain admitted in the hospital from admission until discharge.",
    "purpose": "Improve inpatient efficiency, reduce unnecessary hospitalization, optimize bed turnover, and lower operational cost.",
    "criticality": "Impacts capacity, finance and patient flow",
    "aiOpportunity": "Predict discharge readiness"
  },
  {
    "id": "hospital-l4-05",
    "name": "Bed Occupancy Rate",
    "arabicName": "معدل إشغال الأسرة",
    "level": "L4",
    "item": 5,
    "type": "Operational",
    "category": "Real-Time",
    "family": "F4 / G15 Inpatient & Bed Management Operations",
    "owner": "COO",
    "department": "Bed Management",
    "objective": "Optimize hospital-wide bed utilization",
    "unit": "%",
    "formula": "Occupied beds ÷ Total beds × 100",
    "source": "HIS / Bed Mgmt",
    "refresh": "Hourly",
    "target": "80–85%",
    "definition": "Measures the percentage of occupied inpatient beds relative to total available hospital beds.",
    "purpose": "Monitor hospital capacity utilization, support operational planning, and improve patient-flow management.",
    "criticality": "Core command-center KPI for operational visibility",
    "aiOpportunity": "Predict bed shortages"
  },
  {
    "id": "hospital-l4-06",
    "name": "Discharge Before Noon Rate",
    "arabicName": "معدل خروج المرضى قبل الظهر",
    "level": "L4",
    "item": 6,
    "type": "Operational Flow",
    "category": "Leading",
    "family": "F4 / G16 Patient Flow, Transfer & Discharge Operations",
    "owner": "COO",
    "department": "Nursing / Inpatient Operations",
    "objective": "Accelerate throughput and improve bed availability",
    "unit": "%",
    "formula": "Discharges before noon ÷ Total discharges × 100",
    "source": "HIS / Nursing System",
    "refresh": "Daily",
    "target": ">40%",
    "definition": "Measures the percentage of inpatient discharges completed before noon relative to total daily discharges.",
    "purpose": "Accelerate patient throughput, improve bed availability, and reduce ED boarding and admission delays.",
    "criticality": "executive visibility dependendency",
    "aiOpportunity": "Predict discharge bottlenecks"
  },
  {
    "id": "hospital-l4-07",
    "name": "Cesarean Section Rate",
    "arabicName": "معدل العمليات القيصرية",
    "level": "L4",
    "item": 7,
    "type": "Women Health",
    "category": "Lagging",
    "family": "F5 / G17 Maternal & Obstetrics Services",
    "owner": "CMO / OB Director",
    "department": "OB/GYN",
    "objective": "Monitor maternal-care quality and delivery patterns",
    "unit": "%",
    "formula": "C-section deliveries ÷ Total deliveries × 100",
    "source": "EMR / Obstetrics System",
    "refresh": "Monthly",
    "target": "WHO benchmark",
    "definition": "Measures the percentage of deliveries performed through cesarean section relative to total births.",
    "purpose": "Monitor maternal-care quality, ensure evidence-based obstetric practice, and manage delivery-risk patterns.",
    "criticality": "Major KPI for women-health excellence at Hospital Name",
    "aiOpportunity": "Predict high-risk deliveries"
  },
  {
    "id": "hospital-l4-08",
    "name": "NICU Admission Rate",
    "arabicName": "معدل إدخال حديثي الولادة إلى العناية المركزة",
    "level": "L4",
    "item": 8,
    "type": "Pediatric Care",
    "category": "Leading",
    "family": "F5 / G18 Neonatal, NICU & Pediatric Services",
    "owner": "CMO / NICU Director",
    "department": "NICU / Pediatrics",
    "objective": "Monitor neonatal complications and critical-care demand",
    "unit": "%",
    "formula": "NICU admissions ÷ Live births × 100",
    "source": "EMR / NICU System",
    "refresh": "Monthly",
    "target": "Benchmark target",
    "definition": "Measures the percentage of newborns admitted to the Neonatal Intensive Care Unit relative to total live births.",
    "purpose": "Monitor neonatal complications, assess maternal-child health quality, and optimize NICU resource planning.",
    "criticality": "Critical for maternal-child tertiary-care services",
    "aiOpportunity": "Predict neonatal complications"
  },
  {
    "id": "hospital-l4-09",
    "name": "IVF Clinical Pregnancy Rate",
    "arabicName": "معدل نجاح الحمل السريري لعمليات أطفال الأنابيب",
    "level": "L4",
    "item": 9,
    "type": "Specialized Care",
    "category": "Lagging",
    "family": "F5 / G19 Women Wellness, IVF & Preventive Care",
    "owner": "Women Health Director",
    "department": "IVF Center",
    "objective": "Measure IVF clinical effectiveness and patient outcomes",
    "unit": "%",
    "formula": "Successful pregnancies ÷ IVF cycles × 100",
    "source": "IVF System / EMR",
    "refresh": "Monthly",
    "target": "International benchmark",
    "definition": "Measures the percentage of IVF treatment cycles resulting in confirmed clinical pregnancies.",
    "purpose": "Evaluate IVF program effectiveness, improve fertility-service quality, and enhance women-health outcomes.",
    "criticality": "Key strategic specialty program for Hospital Name",
    "aiOpportunity": "Predict IVF success probability"
  },
  {
    "id": "hospital-l4-10",
    "name": "OR Utilization Rate",
    "arabicName": "معدل استغلال غرف العمليات",
    "level": "L4",
    "item": 10,
    "type": "Surgical Operations",
    "category": "Real-Time",
    "family": "F6 / G22 Surgical & Operating Room Services",
    "owner": "COO / OR Director",
    "department": "Surgery / OR Operations",
    "objective": "Optimize OR efficiency and surgical throughput",
    "unit": "%",
    "formula": "Used OR hours ÷ Available OR hours × 100",
    "source": "OR Scheduling System",
    "refresh": "Daily",
    "target": ">80%",
    "definition": "Measures the percentage of actual utilized operating-room hours relative to total available operating-room hours.",
    "purpose": "Optimize surgical throughput, maximize OR efficiency, reduce idle capacity, and improve surgery scheduling performance.",
    "criticality": "Operational intelligence model",
    "aiOpportunity": "Predict OR bottlenecks and cancellation risks"
  },
  {
    "id": "hospital-l5-01",
    "name": "Laboratory Turnaround Time (TAT)",
    "arabicName": "زمن إنجاز نتائج المختبر",
    "level": "L5",
    "item": 1,
    "type": "Diagnostics Operations",
    "category": "Real-Time",
    "family": "F7 / G25 Laboratory & Blood Bank Services",
    "owner": "COO / Lab Director",
    "department": "Laboratory",
    "objective": "Accelerate diagnostic result delivery and clinical decision-making",
    "unit": "Minutes",
    "formula": "Result release time − order time",
    "source": "LIS",
    "refresh": "Hourly",
    "target": "Benchmark by test type",
    "definition": "Measures the average time required from laboratory test order placement until final result availability and release.",
    "purpose": "Accelerate diagnosis, improve clinical decision-making, reduce treatment delays, and improve patient throughput.",
    "criticality": "Core KPI for inpatient, ED and ICU responsiveness",
    "aiOpportunity": "Predict lab backlog and delays"
  },
  {
    "id": "hospital-l5-02",
    "name": "Critical Lab Result Notification Compliance",
    "arabicName": "معدل الالتزام بإبلاغ النتائج الحرجة للمختبر",
    "level": "L5",
    "item": 2,
    "type": "Patient Safety",
    "category": "Leading",
    "family": "F7 / G25 Laboratory & Blood Bank Services",
    "owner": "CMO / Lab Director",
    "department": "Laboratory / Clinical Units",
    "objective": "Ensure urgent clinical results are communicated rapidly",
    "unit": "%",
    "formula": "Timely critical notifications ÷ Total critical results × 100",
    "source": "LIS / EMR",
    "refresh": "Real-Time",
    "target": ">95%",
    "definition": "Measures the percentage of critical laboratory results communicated to clinicians within the required notification timeframe.",
    "purpose": "Improve patient safety, ensure rapid intervention, and reduce risks associated with delayed critical-result escalation.",
    "criticality": "Directly impacts patient safety and emergency care",
    "aiOpportunity": "Predict escalation risk"
  },
  {
    "id": "hospital-l5-03",
    "name": "Radiology Report Turnaround Time",
    "arabicName": "زمن إصدار تقارير الأشعة",
    "level": "L5",
    "item": 3,
    "type": "Diagnostics Operations",
    "category": "Real-Time",
    "family": "F7 / G26 Radiology, Imaging & Diagnostic Services",
    "owner": "COO / Radiology Director",
    "department": "Radiology",
    "objective": "Reduce imaging-report delays and improve throughput",
    "unit": "Hours",
    "formula": "Signed report time − imaging completion time",
    "source": "RIS / PACS",
    "refresh": "Hourly",
    "target": "<2 hrs urgent cases",
    "definition": "Measures the average time between completion of imaging procedures and final radiology report release.",
    "purpose": "Reduce diagnostic delays, improve emergency and inpatient throughput, and support faster clinical decisions.",
    "criticality": "Essential for ED, surgery and specialty operations",
    "aiOpportunity": "Predict radiology bottlenecks"
  },
  {
    "id": "hospital-l5-04",
    "name": "Imaging Equipment Utilization Rate",
    "arabicName": "معدل استغلال أجهزة التصوير الطبي",
    "level": "L5",
    "item": 4,
    "type": "Operational",
    "category": "Real-Time",
    "family": "F7 / G26 Radiology, Imaging & Diagnostic Services",
    "owner": "COO",
    "department": "Radiology / Biomedical",
    "objective": "Optimize MRI, CT and imaging capacity utilization",
    "unit": "%",
    "formula": "Used equipment hours ÷ Available hours × 100",
    "source": "RIS / Equipment Monitoring",
    "refresh": "Daily",
    "target": ">80%",
    "definition": "Measures the percentage of actual utilized imaging-equipment operational time compared to total available operating time.",
    "purpose": "Optimize MRI, CT, ultrasound, and radiology asset utilization while reducing idle capacity.",
    "criticality": "Maximizes high-cost asset utilization",
    "aiOpportunity": "Predict imaging demand surges"
  },
  {
    "id": "hospital-l5-05",
    "name": "Cath Lab Procedure Success Rate",
    "arabicName": "معدل نجاح إجراءات قسطرة القلب",
    "level": "L5",
    "item": 5,
    "type": "Clinical Outcomes",
    "category": "Lagging",
    "family": "F7 / G27 Cath Lab, Endoscopy & Interventional Services",
    "owner": "CMO / Cath Lab Director",
    "department": "Cath Lab",
    "objective": "Improve interventional-procedure outcomes",
    "unit": "%",
    "formula": "Successful procedures ÷ Total procedures × 100",
    "source": "Cath Lab System / EMR",
    "refresh": "Monthly",
    "target": ">95%",
    "definition": "Measures the percentage of successful cardiac catheterization procedures completed without major procedural complications.",
    "purpose": "Monitor procedural quality, improve cardiovascular outcomes, and support advanced specialty-care excellence.",
    "criticality": "Critical for future advanced specialty expansion",
    "aiOpportunity": "Predict high-risk procedures"
  },
  {
    "id": "hospital-l5-06",
    "name": "Endoscopy Procedure Cancellation Rate",
    "arabicName": "معدل إلغاء إجراءات المناظير",
    "level": "L5",
    "item": 6,
    "type": "Operational",
    "category": "Leading",
    "family": "F7 / G27 Cath Lab, Endoscopy & Interventional Services",
    "owner": "COO",
    "department": "Endoscopy Unit",
    "objective": "Reduce unused procedural capacity",
    "unit": "%",
    "formula": "Cancelled procedures ÷ Scheduled procedures × 100",
    "source": "Scheduling System",
    "refresh": "Daily",
    "target": "<5%",
    "definition": "Measures the percentage of scheduled endoscopy procedures canceled before execution.",
    "purpose": "Reduce procedural inefficiencies, optimize scheduling, and improve utilization of procedural resources.",
    "criticality": "executive visibility dependendency",
    "aiOpportunity": "Predict cancellations"
  },
  {
    "id": "hospital-l5-07",
    "name": "Medication Error Rate",
    "arabicName": "معدل أخطاء الأدوية",
    "level": "L5",
    "item": 7,
    "type": "Patient Safety",
    "category": "Lagging",
    "family": "F7 / G28 Pharmacy & Medication Management",
    "owner": "CMO / Pharmacy Director",
    "department": "Pharmacy",
    "objective": "Improve medication safety and reduce harm",
    "unit": "Rate",
    "formula": "Medication errors ÷ Total medication orders × 1000",
    "source": "Pharmacy System / EMR",
    "refresh": "Monthly",
    "target": "Minimal benchmark",
    "definition": "Measures the frequency of medication-related errors during prescribing, dispensing, administration, or monitoring processes.",
    "purpose": "Improve medication safety, reduce patient harm, and enhance clinical quality and pharmacy governance.",
    "criticality": "One of the most critical patient-safety KPIs",
    "aiOpportunity": "Predict medication-error risk"
  },
  {
    "id": "hospital-l5-08",
    "name": "Pharmacy Stockout Rate",
    "arabicName": "معدل نفاد الأدوية من الصيدلية",
    "level": "L5",
    "item": 8,
    "type": "Operational",
    "category": "Leading",
    "family": "F7 / G28 Pharmacy & Medication Management",
    "owner": "COO / Pharmacy Director",
    "department": "Pharmacy / Supply Chain",
    "objective": "Ensure medication availability and continuity of care",
    "unit": "%",
    "formula": "Stockout medications ÷ Total medications × 100",
    "source": "ERP / Pharmacy System",
    "refresh": "Daily",
    "target": "<1%",
    "definition": "Measures the percentage of medications unavailable when requested due to stock depletion or inventory shortages.",
    "purpose": "Ensure medication availability, maintain continuity of care, and reduce treatment disruption risks.",
    "criticality": "Critical for ICU, ED and chronic-care continuity",
    "aiOpportunity": "Predict medication shortages"
  },
  {
    "id": "hospital-l5-09",
    "name": "Rehabilitation Functional Improvement Score",
    "arabicName": "درجة التحسن الوظيفي في التأهيل الطبي",
    "level": "L5",
    "item": 9,
    "type": "Clinical Outcomes",
    "category": "Lagging",
    "family": "F7 / G29 Rehabilitation, Physiotherapy & Therapeutic Services",
    "owner": "CMO",
    "department": "Rehabilitation Services",
    "objective": "Measure rehabilitation effectiveness and recovery outcomes",
    "unit": "Score",
    "formula": "Standardized functional-improvement scoring",
    "source": "Rehab System / EMR",
    "refresh": "Monthly",
    "target": "Benchmark target",
    "definition": "Measures the level of functional improvement achieved by rehabilitation patients using standardized clinical assessment tools.",
    "purpose": "Evaluate rehabilitation effectiveness, improve recovery outcomes, and optimize physiotherapy-service quality.",
    "criticality": "Important for post-surgical and long-stay recovery optimization",
    "aiOpportunity": "Predict recovery progression"
  },
  {
    "id": "hospital-l5-10",
    "name": "Hospital Acquired Infection (HAI) Rate",
    "arabicName": "معدل العدوى المكتسبة داخل المستشفى",
    "level": "L5",
    "item": 10,
    "type": "Infection Control",
    "category": "Lagging",
    "family": "F8 / G32 Infection Prevention & Control",
    "owner": "Infection Control Director",
    "department": "Infection Prevention & Control",
    "objective": "Reduce healthcare-associated infections",
    "unit": "Rate",
    "formula": "HAI cases ÷ Patient days × 1000",
    "source": "Infection Control System / EMR",
    "refresh": "Monthly",
    "target": "International benchmark",
    "definition": "Measures the frequency of infections acquired during hospitalization relative to patient exposure or patient days.",
    "purpose": "Improve patient safety, reduce infection spread, maintain accreditation standards, and enhance clinical quality outcomes.",
    "criticality": "Operational intelligence model",
    "aiOpportunity": "Predict outbreak and infection clusters"
  },
  {
    "id": "hospital-l6-01",
    "name": "Clinical Documentation Coding Accuracy Rate",
    "arabicName": "معدل دقة ترميز التوثيق السريري",
    "level": "L6",
    "item": 1,
    "type": "Health Information Management",
    "category": "Leading",
    "family": "F10 / G37 Health Information Management, Coding & Medical Records",
    "owner": "CFO / HIM Director",
    "department": "HIM / Coding",
    "objective": "Improve coding quality and reimbursement accuracy",
    "unit": "%",
    "formula": "Accurate coded charts ÷ Audited charts × 100",
    "source": "HIM / Coding System",
    "refresh": "Weekly",
    "target": ">95%",
    "definition": "Measures the percentage of clinical records coded accurately according to ICD, DRG, and medical-coding standards after auditing.",
    "purpose": "Improve coding quality, optimize reimbursement accuracy, reduce claim denials, and ensure regulatory compliance.",
    "criticality": "Critical for DRG optimization, claims and compliance",
    "aiOpportunity": "Predict coding anomalies and revenue leakage"
  },
  {
    "id": "hospital-l6-02",
    "name": "Discharged Not Final Billed (DNFB) Rate",
    "arabicName": "معدل المرضى الخارجين غير المفوترين نهائياً",
    "level": "L6",
    "item": 2,
    "type": "Revenue Cycle",
    "category": "Leading",
    "family": "F10 / G38 Revenue Cycle & Billing Operations",
    "owner": "CFO",
    "department": "Revenue Cycle / Billing",
    "objective": "Accelerate billing cycle completion",
    "unit": "%",
    "formula": "DNFB accounts ÷ Total discharged accounts × 100",
    "source": "Billing System / HIS",
    "refresh": "Daily",
    "target": "<5%",
    "definition": "Measures the percentage of discharged patient accounts that have not yet completed final billing processing.",
    "purpose": "Accelerate revenue realization, reduce billing delays, and improve hospital cash-flow efficiency.",
    "criticality": "Directly impacts hospital cash flow and revenue realization",
    "aiOpportunity": "Predict delayed billing accounts"
  },
  {
    "id": "hospital-l6-03",
    "name": "Net Collection Rate",
    "arabicName": "معدل التحصيل الصافي",
    "level": "L6",
    "item": 3,
    "type": "Financial",
    "category": "Lagging",
    "family": "F10 / G38 Revenue Cycle & Billing Operations",
    "owner": "CFO",
    "department": "Finance / Revenue Cycle",
    "objective": "Maximize collected hospital revenue",
    "unit": "%",
    "formula": "Net collected revenue ÷ Net collectible revenue × 100",
    "source": "ERP / Revenue Cycle System",
    "refresh": "Monthly",
    "target": ">95%",
    "definition": "Measures the percentage of collectible revenue successfully collected after adjustments, denials, and write-offs.",
    "purpose": "Evaluate effectiveness of revenue-cycle operations and maximize hospital financial performance.",
    "criticality": "Core executive financial KPI",
    "aiOpportunity": "Forecast collection performance"
  },
  {
    "id": "hospital-l6-04",
    "name": "Claim Rejection / Denial Rate",
    "arabicName": "معدل رفض أو إنكار المطالبات التأمينية",
    "level": "L6",
    "item": 4,
    "type": "Insurance & Claims",
    "category": "Leading",
    "family": "F10 / G39 Claims, Payer & Insurance Management",
    "owner": "CFO",
    "department": "Claims Management",
    "objective": "Reduce claim denials and payer leakage",
    "unit": "%",
    "formula": "Denied claims ÷ Total submitted claims × 100",
    "source": "Claims Platform / NPHIES",
    "refresh": "Daily",
    "target": "<5%",
    "definition": "Measures the percentage of submitted insurance claims rejected or denied by payers.",
    "purpose": "Reduce revenue leakage, improve claims quality, and optimize payer-management efficiency.",
    "criticality": "Critical in Saudi payer ecosystem and NPHIES operations",
    "aiOpportunity": "Predict denial patterns and root causes"
  },
  {
    "id": "hospital-l6-05",
    "name": "Average Claim Settlement Time",
    "arabicName": "متوسط زمن تسوية المطالبات",
    "level": "L6",
    "item": 5,
    "type": "Insurance Operations",
    "category": "Lagging",
    "family": "F10 / G39 Claims, Payer & Insurance Management",
    "owner": "CFO",
    "department": "Finance / Insurance",
    "objective": "Improve payer cash-conversion cycle",
    "unit": "Days",
    "formula": "Avg payment date − claim submission date",
    "source": "ERP / Claims Platform",
    "refresh": "Weekly",
    "target": "<45 days",
    "definition": "Measures the average time required for insurance payers to process and settle submitted claims.",
    "purpose": "Improve cash-flow predictability, reduce accounts receivable aging, and enhance payer performance management.",
    "criticality": "Important for hospital liquidity and financial planning",
    "aiOpportunity": "Predict delayed payer settlements"
  },
  {
    "id": "hospital-l6-06",
    "name": "Operating Margin",
    "arabicName": "هامش التشغيل",
    "level": "L6",
    "item": 6,
    "type": "Financial Performance",
    "category": "Lagging",
    "family": "F10 / G40 Financial Planning, Costing & Profitability",
    "owner": "CFO / CEO",
    "department": "Finance",
    "objective": "Measure enterprise financial sustainability",
    "unit": "%",
    "formula": "(Operating revenue − operating expense) ÷ operating revenue × 100",
    "source": "ERP / Finance",
    "refresh": "Monthly",
    "target": "Benchmark target",
    "definition": "Measures the percentage difference between operating revenue and operating expenses relative to operating revenue.",
    "purpose": "Assess financial sustainability, profitability, and operational efficiency of the hospital.",
    "criticality": "executive visibility dependendency",
    "aiOpportunity": "Predict financial stress"
  },
  {
    "id": "hospital-l6-07",
    "name": "Cost per Patient Day",
    "arabicName": "تكلفة المريض اليومية",
    "level": "L6",
    "item": 7,
    "type": "Cost Management",
    "category": "Lagging",
    "family": "F10 / G40 Financial Planning, Costing & Profitability",
    "owner": "CFO",
    "department": "Finance / Operations",
    "objective": "Optimize operational cost efficiency",
    "unit": "SAR",
    "formula": "Total inpatient operational cost ÷ Patient days",
    "source": "ERP / HIS",
    "refresh": "Monthly",
    "target": "Benchmark target",
    "definition": "Measures the average operational cost incurred per inpatient per day of hospitalization.",
    "purpose": "Monitor operational efficiency, optimize cost management, and benchmark hospital financial performance.",
    "criticality": "Important for benchmarking and efficiency management",
    "aiOpportunity": "Detect abnormal cost patterns"
  },
  {
    "id": "hospital-l6-08",
    "name": "Inventory Stockout Rate",
    "arabicName": "معدل نفاد المخزون",
    "level": "L6",
    "item": 8,
    "type": "Supply Chain",
    "category": "Leading",
    "family": "F12 / G45 Supply Chain & Materials Management",
    "owner": "COO / Supply Chain Director",
    "department": "Supply Chain",
    "objective": "Ensure uninterrupted clinical supply availability",
    "unit": "%",
    "formula": "Stockout items ÷ Total inventory items × 100",
    "source": "ERP / Inventory System",
    "refresh": "Daily",
    "target": "<2%",
    "definition": "Measures the percentage of inventory items unavailable when requested due to stock depletion.",
    "purpose": "Ensure continuity of clinical operations, reduce treatment delays, and optimize supply-chain performance.",
    "criticality": "Directly impacts surgery, ICU and pharmacy continuity",
    "aiOpportunity": "Predict inventory shortages"
  },
  {
    "id": "hospital-l6-09",
    "name": "Medical Equipment Uptime",
    "arabicName": "معدل جاهزية وتشغيل الأجهزة الطبية",
    "level": "L6",
    "item": 9,
    "type": "Biomedical Engineering",
    "category": "Real-Time",
    "family": "F12 / G46 Biomedical Engineering & Medical Equipment",
    "owner": "COO",
    "department": "Biomedical Engineering",
    "objective": "Ensure critical equipment operational readiness",
    "unit": "%",
    "formula": "Equipment uptime ÷ Total available time × 100",
    "source": "CMMS / Monitoring Tools",
    "refresh": "Real-Time",
    "target": ">98%",
    "definition": "Measures the percentage of time medical equipment remains operational and available for clinical use.",
    "purpose": "Ensure clinical-service continuity, reduce equipment downtime, and improve biomedical reliability.",
    "criticality": "Critical for ICU, OR, imaging and patient safety",
    "aiOpportunity": "Predict equipment failures"
  },
  {
    "id": "hospital-l6-10",
    "name": "Facility Critical Utility Downtime",
    "arabicName": "زمن تعطل المرافق والخدمات الحيوية",
    "level": "L6",
    "item": 10,
    "type": "Facility Operations",
    "category": "Real-Time",
    "family": "F12 / G47 Facility Operations, Safety & Environmental Services",
    "owner": "COO",
    "department": "Facilities Management",
    "objective": "Minimize operational disruption from utilities failures",
    "unit": "Hours",
    "formula": "Total downtime duration for critical utilities",
    "source": "Facility Mgmt System / BMS",
    "refresh": "Real-Time",
    "target": "Minimal downtime",
    "definition": "Measures the total duration of outages affecting critical hospital utilities such as electricity, water, HVAC, oxygen, or medical gases.",
    "purpose": "Maintain operational resilience, ensure patient safety, and minimize disruption to clinical services.",
    "criticality": "Operational intelligence model",
    "aiOpportunity": "Predict infrastructure failures and outages"
  },
  {
    "id": "hospital-l7-01",
    "name": "Workforce Vacancy Rate",
    "arabicName": "معدل الشواغر الوظيفية",
    "level": "L7",
    "item": 1,
    "type": "Workforce Management",
    "category": "Leading",
    "family": "F11 / G41 Workforce, Staffing & Productivity Management",
    "owner": "CHRO",
    "department": "HR",
    "objective": "Ensure workforce sufficiency and staffing continuity",
    "unit": "%",
    "formula": "Vacant approved positions ÷ Total approved positions × 100",
    "source": "HRIS",
    "refresh": "Monthly",
    "target": "<10%",
    "definition": "Measures the percentage of approved positions that remain vacant within the hospital workforce structure.",
    "purpose": "Identify staffing shortages, support workforce planning, and ensure operational and clinical service continuity.",
    "criticality": "Critical for hospital operational continuity and service capacity",
    "aiOpportunity": "Predict staffing shortages"
  },
  {
    "id": "hospital-l7-02",
    "name": "Workforce Productivity Index",
    "arabicName": "مؤشر إنتاجية القوى العاملة",
    "level": "L7",
    "item": 2,
    "type": "Workforce Operations",
    "category": "Operational",
    "family": "F11 / G41 Workforce, Staffing & Productivity Management",
    "owner": "COO / CHRO",
    "department": "HR / Operations",
    "objective": "Optimize workforce efficiency and utilization",
    "unit": "Score",
    "formula": "Weighted productivity formula based on output vs staffing",
    "source": "HRIS / HIS",
    "refresh": "Monthly",
    "target": "Target benchmark",
    "definition": "Measures workforce efficiency based on productivity outputs relative to staffing levels, workload, and operational targets.",
    "purpose": "Optimize workforce utilization, improve operational efficiency, and support resource planning decisions.",
    "criticality": "Measures operational efficiency across departments",
    "aiOpportunity": "Predict productivity decline"
  },
  {
    "id": "hospital-l7-03",
    "name": "Employee Turnover Rate",
    "arabicName": "معدل دوران الموظفين",
    "level": "L7",
    "item": 3,
    "type": "Workforce Management",
    "category": "Lagging",
    "family": "F11 / G41 Workforce, Staffing & Productivity Management",
    "owner": "CHRO",
    "department": "HR",
    "objective": "Reduce talent loss and improve workforce stability",
    "unit": "%",
    "formula": "Employee exits ÷ Avg workforce size × 100",
    "source": "HRIS",
    "refresh": "Monthly",
    "target": "<10%",
    "definition": "Measures the percentage of employees who leave the organization during a defined period relative to the average workforce size.",
    "purpose": "Monitor workforce stability, reduce talent loss, improve retention strategies, and control replacement costs.",
    "criticality": "High turnover impacts continuity, quality and cost",
    "aiOpportunity": "Predict attrition risk"
  },
  {
    "id": "hospital-l7-04",
    "name": "Nursing Hours per Patient Day (NHPPD)",
    "arabicName": "عدد ساعات التمريض لكل مريض يومياً",
    "level": "L7",
    "item": 4,
    "type": "Nursing Operations",
    "category": "Operational",
    "family": "F11 / G42 Nursing Operations & Clinical Workforce Excellence",
    "owner": "CNO",
    "department": "Nursing",
    "objective": "Optimize nurse staffing and patient-care quality",
    "unit": "Hours",
    "formula": "Total nursing hours ÷ Patient days",
    "source": "HRIS / HIS",
    "refresh": "Daily",
    "target": "Benchmark by specialty",
    "definition": "Measures the average number of nursing care hours delivered per inpatient per day.",
    "purpose": "Ensure safe staffing levels, improve patient-care quality, and optimize nursing workforce allocation.",
    "criticality": "Core patient-safety and quality KPI",
    "aiOpportunity": "Predict unsafe staffing conditions"
  },
  {
    "id": "hospital-l7-05",
    "name": "Nursing Competency Compliance Rate",
    "arabicName": "معدل الالتزام بكفاءات التمريض",
    "level": "L7",
    "item": 5,
    "type": "Clinical Workforce",
    "category": "Leading",
    "family": "F11 / G42 Nursing Operations & Clinical Workforce Excellence",
    "owner": "CNO / HR Director",
    "department": "Nursing Education",
    "objective": "Ensure nursing competency and certification readiness",
    "unit": "%",
    "formula": "Competent/certified nurses ÷ Total nurses × 100",
    "source": "LMS / HRIS",
    "refresh": "Monthly",
    "target": ">95%",
    "definition": "Measures the percentage of nursing staff meeting mandatory competency, certification, and training requirements.",
    "purpose": "Maintain clinical competency, accreditation readiness, patient safety, and nursing-care quality standards.",
    "criticality": "Critical for accreditation and patient safety",
    "aiOpportunity": "Predict competency gaps"
  },
  {
    "id": "hospital-l7-06",
    "name": "Overtime Utilization Rate",
    "arabicName": "معدل استخدام العمل الإضافي",
    "level": "L7",
    "item": 6,
    "type": "Workforce Operations",
    "category": "Lagging",
    "family": "F11 / G42 Nursing Operations & Clinical Workforce Excellence",
    "owner": "CHRO / CNO",
    "department": "HR / Nursing",
    "objective": "Reduce burnout and workforce fatigue",
    "unit": "%",
    "formula": "Overtime hours ÷ Total worked hours × 100",
    "source": "HRIS",
    "refresh": "Weekly",
    "target": "<10%",
    "definition": "Measures the percentage of overtime hours relative to total worked hours across the workforce or nursing teams.",
    "purpose": "Monitor workforce fatigue, reduce burnout risks, and optimize staffing and scheduling efficiency.",
    "criticality": "executive visibility dependendency",
    "aiOpportunity": "Predict burnout and staffing shortages"
  },
  {
    "id": "hospital-l7-07",
    "name": "Residency Program Utilization Rate",
    "arabicName": "معدل استغلال برامج الإقامة الطبية",
    "level": "L7",
    "item": 7,
    "type": "Academic Medicine",
    "category": "Operational",
    "family": "F11 / G43 Academic Medicine, Residency & Simulation Programs",
    "owner": "Dean / Academic Affairs Director",
    "department": "Academic Affairs",
    "objective": "Optimize residency deployment and educational coverage",
    "unit": "%",
    "formula": "Active residents ÷ Planned residents × 100",
    "source": "Academic Mgmt System",
    "refresh": "Monthly",
    "target": ">90%",
    "definition": "Measures the percentage of available residency-program capacity actively utilized by medical residents.",
    "purpose": "Optimize academic-training capacity, improve teaching-hospital effectiveness, and support medical education objectives.",
    "criticality": "Important for university-hospital teaching mission",
    "aiOpportunity": "Predict residency capacity gaps"
  },
  {
    "id": "hospital-l7-08",
    "name": "Simulation Center Utilization Rate",
    "arabicName": "معدل استغلال مركز المحاكاة الطبية",
    "level": "L7",
    "item": 8,
    "type": "Academic Medicine",
    "category": "Operational",
    "family": "F11 / G43 Academic Medicine, Residency & Simulation Programs",
    "owner": "Academic Affairs Director",
    "department": "Simulation Center",
    "objective": "Maximize educational and clinical-training utilization",
    "unit": "%",
    "formula": "Used simulation sessions ÷ Available sessions × 100",
    "source": "Scheduling System",
    "refresh": "Monthly",
    "target": ">80%",
    "definition": "Measures the percentage of simulation-center sessions and facilities actively utilized compared to total available capacity.",
    "purpose": "Maximize educational value, improve clinical-training effectiveness, and support academic healthcare excellence.",
    "criticality": "Hospital Name has one of the region’s major simulation centers",
    "aiOpportunity": "Predict training demand patterns"
  },
  {
    "id": "hospital-l7-09",
    "name": "Research Publication Volume",
    "arabicName": "حجم النشر البحثي",
    "level": "L7",
    "item": 9,
    "type": "Research & Innovation",
    "category": "Lagging",
    "family": "F11 / G44 Research, Innovation & Clinical Trials",
    "owner": "Research Director",
    "department": "Research Center",
    "objective": "Improve academic output and institutional ranking",
    "unit": "Count",
    "formula": "Total peer-reviewed publications",
    "source": "Research Platform",
    "refresh": "Quarterly",
    "target": "Growth target",
    "definition": "Measures the total number of peer-reviewed research publications produced by the hospital and affiliated academic teams.",
    "purpose": "Strengthen academic reputation, research productivity, innovation capability, and institutional ranking.",
    "criticality": "Critical for academic-medical-center positioning",
    "aiOpportunity": "Predict research productivity trends"
  },
  {
    "id": "hospital-l7-10",
    "name": "Clinical Trial Enrollment Rate",
    "arabicName": "معدل التسجيل في التجارب السريرية",
    "level": "L7",
    "item": 10,
    "type": "Research Operations",
    "category": "Leading",
    "family": "F11 / G44 Research, Innovation & Clinical Trials",
    "owner": "Research Director / CMO",
    "department": "Research / Clinical Departments",
    "objective": "Increase participation in clinical trials and innovation programs",
    "unit": "%",
    "formula": "Enrolled participants ÷ Eligible participants × 100",
    "source": "CTMS / EMR",
    "refresh": "Monthly",
    "target": "Benchmark target",
    "definition": "Measures the percentage of eligible patients successfully enrolled into approved clinical trials and research studies.",
    "purpose": "Enhance research participation, support innovation, and expand advanced evidence-based clinical programs.",
    "criticality": "Operational intelligence model",
    "aiOpportunity": "Predict enrollment feasibility and trial performance"
  }
] satisfies HealthcareKpi[];

export const healthcareKpiImportContract = [
  "Workbook source: Hospital Name - KPI Master.xlsx.",
  "Imported worksheets: L1, L2, L3, L4, L5, L6, and L7.",
  "Each KPI keeps its Arabic name, owner, department, formula, source system, refresh frequency, benchmark target, criticality note, and AI opportunity.",
  "Dashboard packs are assigned from the Relevant Family / Group field so the landing page mirrors the catalogue structure.",
];

export const executiveLenses = [
  {
    id: "ceo",
    title: "CEO View",
    role: "Enterprise leadership",
    mandate: "Strategy execution, governance assurance, safety posture, and transformation momentum.",
    boardQuestion: "Is Hospital Name moving the right enterprise measures fast enough?",
    dashboardPackIds: ["executive-performance", "predictive-radar"],
    kpiIds: ["hospital-l1-01", "hospital-l1-02", "hospital-l1-03", "hospital-l1-04"],
  },
  {
    id: "coo",
    title: "COO View",
    role: "Operations command",
    mandate: "Access, flow, capacity, ED pressure, diagnostics throughput, and service resilience.",
    boardQuestion: "Where is operational pressure building before it becomes visible to patients?",
    dashboardPackIds: ["patient-flow-acute", "patient-access-experience", "diagnostics-therapeutics-safety"],
    kpiIds: ["hospital-l1-10", "hospital-l4-03", "hospital-l4-05", "hospital-l5-01"],
  },
  {
    id: "cfo",
    title: "CFO View",
    role: "Financial stewardship",
    mandate: "Revenue realization, claims friction, margin, cost, supply continuity, and asset uptime.",
    boardQuestion: "Which operational signals are converting into financial risk or opportunity?",
    dashboardPackIds: ["revenue-finance-support", "predictive-radar"],
    kpiIds: ["hospital-l6-02", "hospital-l6-03", "hospital-l6-04", "hospital-l6-06"],
  },
  {
    id: "cio-cmio",
    title: "CIO / CMIO View",
    role: "Digital health leadership",
    mandate: "EMR adoption, clinical documentation, interoperability, analytics reliability, cybersecurity, and AI readiness.",
    boardQuestion: "Can digital, data, and clinical systems sustain trusted hospital intelligence?",
    dashboardPackIds: ["digital-health-data-command", "predictive-radar"],
    kpiIds: ["hospital-l2-01", "hospital-l2-04", "hospital-l2-07", "hospital-l2-09"],
  },
  {
    id: "cmo",
    title: "CMO View",
    role: "Clinical quality and outcomes",
    mandate: "Clinical safety, critical care, infection control, procedural quality, and clinical documentation.",
    boardQuestion: "Which clinical risks need executive attention before quality deteriorates?",
    dashboardPackIds: ["diagnostics-therapeutics-safety", "patient-flow-acute"],
    kpiIds: ["hospital-l5-02", "hospital-l5-05", "hospital-l5-10", "hospital-l6-01"],
  },
  {
    id: "cno",
    title: "CNO View",
    role: "Nursing and care delivery",
    mandate: "Nursing coverage, competency, staffing risk, overtime pressure, and safety-sensitive workload.",
    boardQuestion: "Are staffing and competency levels sufficient for safe care delivery?",
    dashboardPackIds: ["workforce-academic-research", "predictive-radar"],
    kpiIds: ["hospital-l7-04", "hospital-l7-05", "hospital-l7-06", "hospital-l7-01"],
  },
  {
    id: "patient-experience",
    title: "Patient Experience View",
    role: "Access and experience",
    mandate: "Registration, appointment availability, no-shows, referrals, satisfaction, and digital engagement.",
    boardQuestion: "Where does the patient journey create friction, delay, or dissatisfaction?",
    dashboardPackIds: ["patient-access-experience"],
    kpiIds: ["hospital-l3-01", "hospital-l3-03", "hospital-l3-05", "hospital-l3-09"],
  },
  {
    id: "workforce",
    title: "Workforce View",
    role: "People and productivity",
    mandate: "Vacancy, turnover, productivity, nursing hours, overtime, and workforce resilience.",
    boardQuestion: "Where is workforce pressure most likely to affect continuity or quality?",
    dashboardPackIds: ["workforce-academic-research", "predictive-radar"],
    kpiIds: ["hospital-l7-01", "hospital-l7-02", "hospital-l7-03", "hospital-l7-06"],
  },
  {
    id: "research",
    title: "Research View",
    role: "Academic medicine and innovation",
    mandate: "Residency utilization, simulation capacity, publications, and clinical trial participation.",
    boardQuestion: "Is the academic mission converting capacity into research and training impact?",
    dashboardPackIds: ["workforce-academic-research"],
    kpiIds: ["hospital-l7-07", "hospital-l7-08", "hospital-l7-09", "hospital-l7-10"],
  },
] satisfies ExecutiveLens[];

export const healthcareCockpitDashboardPacks = [
  {
    id: "executive-performance",
    title: "Executive Performance Cockpit",
    audience: "CEO, executive committee, board assurance",
    operatingQuestion: "Are strategy, risk, governance, and acute pressure moving in the right direction?",
    demoNarrative: "A single executive landing surface for transformation, accreditation, enterprise risk, and emergency pressure.",
    families: [
      "F1 / G1 Enterprise Strategy & Planning",
      "F1 / G2 Governance, Risk & Compliance",
      "F1 / G3 Enterprise Performance, PMO & Value Realization",
    ],
    kpiIds: ["hospital-l1-01", "hospital-l1-02", "hospital-l1-03", "hospital-l1-04", "hospital-l1-05"],
    lensIds: ["ceo"],
  },
  {
    id: "digital-health-data-command",
    title: "Digital Health & Data Command",
    audience: "CIO, CMIO, CISO, data office",
    operatingQuestion: "Are clinical platforms, interoperability, data quality, and cybersecurity ready for trusted intelligence?",
    demoNarrative: "Shows the digital operating base that every downstream cockpit depends on.",
    families: [
      "F2 / G4 HIS, EMR & Clinical Platforms",
      "F2 / G5 Integration, Interoperability & NPHIES",
      "F2 / G6 Enterprise Data, BI & Analytics",
      "F2 / G7 Cybersecurity, Privacy & Data Protection",
      "F2 / G8 AI, Predictive Intelligence & Automation",
      "F14 / G51-G53 Enterprise Command Center & Predictive Operations",
    ],
    kpiIds: ["hospital-l2-01", "hospital-l2-02", "hospital-l2-04", "hospital-l2-07", "hospital-l2-09"],
    lensIds: ["cio-cmio"],
  },
  {
    id: "patient-access-experience",
    title: "Patient Access & Experience",
    audience: "COO, access teams, patient experience leadership",
    operatingQuestion: "Where are patients waiting, dropping out, or failing to complete the care journey?",
    demoNarrative: "Turns access, identity, referral, authorization, and satisfaction measures into a patient journey cockpit.",
    families: [
      "F3 / G9 Patient Registration & Identity Management",
      "F3 / G10 Appointment, Referral & Scheduling Management",
      "F3 / G11 Insurance Eligibility & Authorization",
      "F3 / G12 Care Coordination & Patient Navigation",
      "F9 / G34 Patient Experience & Satisfaction Management",
      "F9 / G35 Digital Patient Engagement & Telehealth",
    ],
    kpiIds: ["hospital-l3-01", "hospital-l3-03", "hospital-l3-04", "hospital-l3-05", "hospital-l3-09"],
    lensIds: ["coo", "patient-experience"],
  },
  {
    id: "patient-flow-acute",
    title: "Patient Flow & Acute Operations",
    audience: "COO, CMO, ED, ICU, bed command",
    operatingQuestion: "Where is acute pressure forming across ED, ICU, inpatient beds, discharge, and theatres?",
    demoNarrative: "A hospital command layer for acute demand, capacity, flow, and specialty operations.",
    families: [
      "F4 / G13 Emergency Department Operations",
      "F4 / G14 Critical Care & Intensive Care Operations",
      "F4 / G15 Inpatient & Bed Management Operations",
      "F4 / G16 Patient Flow, Transfer & Discharge Operations",
      "F5 / G17 Maternal & Obstetrics Services",
      "F5 / G18 Neonatal, NICU & Pediatric Services",
      "F5 / G19 Women Wellness, IVF & Preventive Care",
      "F6 / G22 Surgical & Operating Room Services",
    ],
    kpiIds: ["hospital-l1-06", "hospital-l1-07", "hospital-l4-03", "hospital-l4-05", "hospital-l4-10"],
    lensIds: ["coo", "cmo"],
  },
  {
    id: "diagnostics-therapeutics-safety",
    title: "Diagnostics, Therapeutics & Safety",
    audience: "CMO, lab, radiology, pharmacy, infection control",
    operatingQuestion: "Are diagnostic, medication, infection, and therapeutic services supporting safe timely care?",
    demoNarrative: "Combines turnaround time, critical-result escalation, procedural quality, medication safety, and infection control.",
    families: [
      "F7 / G25 Laboratory & Blood Bank Services",
      "F7 / G26 Radiology, Imaging & Diagnostic Services",
      "F7 / G27 Cath Lab, Endoscopy & Interventional Services",
      "F7 / G28 Pharmacy & Medication Management",
      "F7 / G29 Rehabilitation, Physiotherapy & Therapeutic Services",
      "F8 / G32 Infection Prevention & Control",
    ],
    kpiIds: ["hospital-l5-01", "hospital-l5-02", "hospital-l5-03", "hospital-l5-07", "hospital-l5-10"],
    lensIds: ["coo", "cmo"],
  },
  {
    id: "revenue-finance-support",
    title: "Revenue, Finance & Support Operations",
    audience: "CFO, revenue cycle, supply chain, biomedical, facilities",
    operatingQuestion: "Which operational issues are affecting liquidity, margin, supply continuity, or asset readiness?",
    demoNarrative: "Connects cash, claims, cost, inventory, equipment, and utilities into one finance-led operating view.",
    families: [
      "F10 / G37 Health Information Management, Coding & Medical Records",
      "F10 / G38 Revenue Cycle & Billing Operations",
      "F10 / G39 Claims, Payer & Insurance Management",
      "F10 / G40 Financial Planning, Costing & Profitability",
      "F12 / G45 Supply Chain & Materials Management",
      "F12 / G46 Biomedical Engineering & Medical Equipment",
      "F12 / G47 Facility Operations, Safety & Environmental Services",
    ],
    kpiIds: ["hospital-l6-02", "hospital-l6-03", "hospital-l6-04", "hospital-l6-08", "hospital-l6-09"],
    lensIds: ["cfo"],
  },
  {
    id: "workforce-academic-research",
    title: "Workforce, Academic Medicine & Research",
    audience: "CHRO, CNO, academic affairs, research leadership",
    operatingQuestion: "Can workforce, education, and research capacity sustain the hospital mission?",
    demoNarrative: "Links staffing, nursing, academic medicine, simulation, research output, and trial enrollment.",
    families: [
      "F11 / G41 Workforce, Staffing & Productivity Management",
      "F11 / G42 Nursing Operations & Clinical Workforce Excellence",
      "F11 / G43 Academic Medicine, Residency & Simulation Programs",
      "F11 / G44 Research, Innovation & Clinical Trials",
    ],
    kpiIds: ["hospital-l7-01", "hospital-l7-04", "hospital-l7-05", "hospital-l7-09", "hospital-l7-10"],
    lensIds: ["cno", "workforce", "research"],
  },
  {
    id: "predictive-radar",
    title: "Predictive Opportunity Radar",
    audience: "Executive committee, analytics, transformation",
    operatingQuestion: "Where can predictive intelligence reduce risk, delay, cost, or safety exposure?",
    demoNarrative: "Prioritizes AI candidates by operational value, source readiness, and governance guardrails.",
    families: [
      "F2 / G8 AI, Predictive Intelligence & Automation",
      "F14 / G51-G53 Enterprise Command Center & Predictive Operations",
      "F4 / G13 Emergency Department Operations",
      "F11 / G41 Workforce, Staffing & Productivity Management",
    ],
    kpiIds: ["hospital-l2-09", "hospital-l2-10", "hospital-l1-10", "hospital-l7-01", "hospital-l6-04"],
    lensIds: ["ceo", "coo", "cfo", "cio-cmio", "cno", "workforce"],
  },
] satisfies HealthcareCockpitDashboardPack[];

export const hospitalIntelligenceDomains = [
  {
    id: "strategy",
    title: "Enterprise Strategy",
    description: "Strategic execution, transformation, accreditation, risk, and executive decision velocity.",
    packIds: ["executive-performance"],
    signal: "Board assurance",
  },
  {
    id: "digital-foundation",
    title: "Digital Foundation",
    description: "EMR, interoperability, analytics availability, data quality, cybersecurity, and AI platform readiness.",
    packIds: ["digital-health-data-command", "predictive-radar"],
    signal: "Trust layer",
  },
  {
    id: "patient-journey",
    title: "Patient Journey",
    description: "Registration, scheduling, referral, authorization, satisfaction, and digital engagement.",
    packIds: ["patient-access-experience"],
    signal: "Access friction",
  },
  {
    id: "acute-operations",
    title: "Acute Operations",
    description: "ED, ICU, bed utilization, discharge discipline, maternal care, pediatric care, and operating theatres.",
    packIds: ["patient-flow-acute"],
    signal: "Capacity pressure",
  },
  {
    id: "quality-safety",
    title: "Quality and Safety",
    description: "Diagnostics, critical-result communication, medication safety, procedure outcomes, and infection control.",
    packIds: ["diagnostics-therapeutics-safety"],
    signal: "Clinical reliability",
  },
  {
    id: "financial-resilience",
    title: "Financial Resilience",
    description: "Coding, billing, collections, denials, settlement time, margin, cost, supplies, equipment, and facilities.",
    packIds: ["revenue-finance-support"],
    signal: "Value protection",
  },
  {
    id: "people-research",
    title: "People and Research",
    description: "Workforce sufficiency, nursing hours, competency, overtime, residency, simulation, publications, and trials.",
    packIds: ["workforce-academic-research"],
    signal: "Mission capacity",
  },
] satisfies HospitalIntelligenceDomain[];

export const predictiveOpportunityRadar = [
  {
    id: "capacity-forecasting",
    title: "Capacity pressure forecasting",
    kpiId: "hospital-l2-09",
    area: "Operations command",
    valueCase: "Anticipate bed, ED, ICU, and staffing pressure before daily escalation meetings.",
    readiness: "High",
    guardrail: "Requires source freshness, forecast validation, and clear escalation thresholds.",
  },
  {
    id: "ed-saturation",
    title: "ED saturation early warning",
    kpiId: "hospital-l1-10",
    area: "Acute flow",
    valueCase: "Detect ED crowding and handover risk early enough to mobilize capacity.",
    readiness: "High",
    guardrail: "Predictions should support operational review, not automate clinical prioritization.",
  },
  {
    id: "denial-patterns",
    title: "Claims denial pattern detection",
    kpiId: "hospital-l6-04",
    area: "Financial resilience",
    valueCase: "Identify denial root causes and payer patterns before they become cash leakage.",
    readiness: "Medium",
    guardrail: "Needs payer, claim, coding, and NPHIES lineage before financial automation.",
  },
  {
    id: "staffing-shortage",
    title: "Workforce shortage prediction",
    kpiId: "hospital-l7-01",
    area: "Workforce resilience",
    valueCase: "Highlight service lines where vacancy and overtime risk may affect continuity.",
    readiness: "Medium",
    guardrail: "Model output must be paired with HR policy and workforce planning review.",
  },
  {
    id: "clinical-documentation-risk",
    title: "Incomplete documentation risk",
    kpiId: "hospital-l2-02",
    area: "Clinical documentation",
    valueCase: "Flag charts likely to miss documentation standards before coding and billing delays occur.",
    readiness: "Medium",
    guardrail: "Needs clinician workflow alignment and non-punitive review design.",
  },
  {
    id: "infection-control-signal",
    title: "Infection-control risk signal",
    kpiId: "hospital-l5-10",
    area: "Clinical safety",
    valueCase: "Surface clusters and early warning signals for HAI surveillance review.",
    readiness: "Emerging",
    guardrail: "Requires strong clinical governance and epidemiology oversight before actioning.",
  },
] satisfies PredictiveOpportunity[];

export function getHealthcareKpiById(id: string) {
  return healthcareKpis.find((kpi) => kpi.id === id) ?? null;
}

export function getHealthcareKpisByIds(ids: string[]) {
  return ids.map(getHealthcareKpiById).filter((kpi): kpi is HealthcareKpi => Boolean(kpi));
}

export function getHealthcareKpisForPack(pack: HealthcareCockpitDashboardPack) {
  const explicit = getHealthcareKpisByIds(pack.kpiIds);
  const familyMatches = healthcareKpis.filter((kpi) => pack.families.includes(kpi.family));
  return Array.from(new Map([...explicit, ...familyMatches].map((kpi) => [kpi.id, kpi])).values());
}

export function getGovernanceReadinessScore(kpis: HealthcareKpi[]) {
  const fields: Array<keyof HealthcareKpi> = ["owner", "department", "formula", "source", "refresh", "target", "definition"];
  const possible = kpis.length * fields.length;
  if (!possible) return 0;
  const complete = kpis.reduce(
    (count, kpi) => count + fields.filter((field) => Boolean(kpi[field])).length,
    0,
  );
  return Math.round((complete / possible) * 100);
}
